// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: qcb/qcbbridge/tx.proto

package qcbbridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName        = "/qcb.qcbbridge.Msg/UpdateParams"
	Msg_SendIbcAgent_FullMethodName        = "/qcb.qcbbridge.Msg/SendIbcAgent"
	Msg_BroadcastAgentState_FullMethodName = "/qcb.qcbbridge.Msg/BroadcastAgentState"
	Msg_PostStateRoot_FullMethodName       = "/qcb.qcbbridge.Msg/PostStateRoot"
	Msg_RegisterChain_FullMethodName       = "/qcb.qcbbridge.Msg/RegisterChain"
	Msg_TokenizeOutput_FullMethodName      = "/qcb.qcbbridge.Msg/TokenizeOutput"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	SendIbcAgent(ctx context.Context, in *MsgSendIbcAgent, opts ...grpc.CallOption) (*MsgSendIbcAgentResponse, error)
	BroadcastAgentState(ctx context.Context, in *MsgBroadcastAgentState, opts ...grpc.CallOption) (*MsgBroadcastAgentStateResponse, error)
	PostStateRoot(ctx context.Context, in *MsgPostStateRoot, opts ...grpc.CallOption) (*MsgPostStateRootResponse, error)
	RegisterChain(ctx context.Context, in *MsgRegisterChain, opts ...grpc.CallOption) (*MsgRegisterChainResponse, error)
	TokenizeOutput(ctx context.Context, in *MsgTokenizeOutput, opts ...grpc.CallOption) (*MsgTokenizeOutputResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendIbcAgent(ctx context.Context, in *MsgSendIbcAgent, opts ...grpc.CallOption) (*MsgSendIbcAgentResponse, error) {
	out := new(MsgSendIbcAgentResponse)
	err := c.cc.Invoke(ctx, Msg_SendIbcAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BroadcastAgentState(ctx context.Context, in *MsgBroadcastAgentState, opts ...grpc.CallOption) (*MsgBroadcastAgentStateResponse, error) {
	out := new(MsgBroadcastAgentStateResponse)
	err := c.cc.Invoke(ctx, Msg_BroadcastAgentState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PostStateRoot(ctx context.Context, in *MsgPostStateRoot, opts ...grpc.CallOption) (*MsgPostStateRootResponse, error) {
	out := new(MsgPostStateRootResponse)
	err := c.cc.Invoke(ctx, Msg_PostStateRoot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterChain(ctx context.Context, in *MsgRegisterChain, opts ...grpc.CallOption) (*MsgRegisterChainResponse, error) {
	out := new(MsgRegisterChainResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterChain_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TokenizeOutput(ctx context.Context, in *MsgTokenizeOutput, opts ...grpc.CallOption) (*MsgTokenizeOutputResponse, error) {
	out := new(MsgTokenizeOutputResponse)
	err := c.cc.Invoke(ctx, Msg_TokenizeOutput_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	SendIbcAgent(context.Context, *MsgSendIbcAgent) (*MsgSendIbcAgentResponse, error)
	BroadcastAgentState(context.Context, *MsgBroadcastAgentState) (*MsgBroadcastAgentStateResponse, error)
	PostStateRoot(context.Context, *MsgPostStateRoot) (*MsgPostStateRootResponse, error)
	RegisterChain(context.Context, *MsgRegisterChain) (*MsgRegisterChainResponse, error)
	TokenizeOutput(context.Context, *MsgTokenizeOutput) (*MsgTokenizeOutputResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) SendIbcAgent(context.Context, *MsgSendIbcAgent) (*MsgSendIbcAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendIbcAgent not implemented")
}
func (UnimplementedMsgServer) BroadcastAgentState(context.Context, *MsgBroadcastAgentState) (*MsgBroadcastAgentStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastAgentState not implemented")
}
func (UnimplementedMsgServer) PostStateRoot(context.Context, *MsgPostStateRoot) (*MsgPostStateRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostStateRoot not implemented")
}
func (UnimplementedMsgServer) RegisterChain(context.Context, *MsgRegisterChain) (*MsgRegisterChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterChain not implemented")
}
func (UnimplementedMsgServer) TokenizeOutput(context.Context, *MsgTokenizeOutput) (*MsgTokenizeOutputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenizeOutput not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendIbcAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendIbcAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendIbcAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SendIbcAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendIbcAgent(ctx, req.(*MsgSendIbcAgent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BroadcastAgentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBroadcastAgentState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BroadcastAgentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_BroadcastAgentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BroadcastAgentState(ctx, req.(*MsgBroadcastAgentState))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PostStateRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPostStateRoot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PostStateRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_PostStateRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PostStateRoot(ctx, req.(*MsgPostStateRoot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterChain(ctx, req.(*MsgRegisterChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TokenizeOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTokenizeOutput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TokenizeOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TokenizeOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TokenizeOutput(ctx, req.(*MsgTokenizeOutput))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qcb.qcbbridge.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SendIbcAgent",
			Handler:    _Msg_SendIbcAgent_Handler,
		},
		{
			MethodName: "BroadcastAgentState",
			Handler:    _Msg_BroadcastAgentState_Handler,
		},
		{
			MethodName: "PostStateRoot",
			Handler:    _Msg_PostStateRoot_Handler,
		},
		{
			MethodName: "RegisterChain",
			Handler:    _Msg_RegisterChain_Handler,
		},
		{
			MethodName: "TokenizeOutput",
			Handler:    _Msg_TokenizeOutput_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qcb/qcbbridge/tx.proto",
}
