// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: qcb/qcbwalletproto/tx.proto

package qcbwalletproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName          = "/qcb.qcbwalletproto.Msg/UpdateParams"
	Msg_RegisterWalletProfile_FullMethodName = "/qcb.qcbwalletproto.Msg/RegisterWalletProfile"
	Msg_SetEncryptionKey_FullMethodName      = "/qcb.qcbwalletproto.Msg/SetEncryptionKey"
	Msg_SetPqKey_FullMethodName              = "/qcb.qcbwalletproto.Msg/SetPqKey"
	Msg_UpdateWalletProfile_FullMethodName   = "/qcb.qcbwalletproto.Msg/UpdateWalletProfile"
	Msg_SetWalletPermissions_FullMethodName  = "/qcb.qcbwalletproto.Msg/SetWalletPermissions"
	Msg_LockWallet_FullMethodName            = "/qcb.qcbwalletproto.Msg/LockWallet"
	Msg_UnlockWallet_FullMethodName          = "/qcb.qcbwalletproto.Msg/UnlockWallet"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	RegisterWalletProfile(ctx context.Context, in *MsgRegisterWalletProfile, opts ...grpc.CallOption) (*MsgRegisterWalletProfileResponse, error)
	SetEncryptionKey(ctx context.Context, in *MsgSetEncryptionKey, opts ...grpc.CallOption) (*MsgSetEncryptionKeyResponse, error)
	SetPqKey(ctx context.Context, in *MsgSetPqKey, opts ...grpc.CallOption) (*MsgSetPqKeyResponse, error)
	UpdateWalletProfile(ctx context.Context, in *MsgUpdateWalletProfile, opts ...grpc.CallOption) (*MsgUpdateWalletProfileResponse, error)
	SetWalletPermissions(ctx context.Context, in *MsgSetWalletPermissions, opts ...grpc.CallOption) (*MsgSetWalletPermissionsResponse, error)
	LockWallet(ctx context.Context, in *MsgLockWallet, opts ...grpc.CallOption) (*MsgLockWalletResponse, error)
	UnlockWallet(ctx context.Context, in *MsgUnlockWallet, opts ...grpc.CallOption) (*MsgUnlockWalletResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterWalletProfile(ctx context.Context, in *MsgRegisterWalletProfile, opts ...grpc.CallOption) (*MsgRegisterWalletProfileResponse, error) {
	out := new(MsgRegisterWalletProfileResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterWalletProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetEncryptionKey(ctx context.Context, in *MsgSetEncryptionKey, opts ...grpc.CallOption) (*MsgSetEncryptionKeyResponse, error) {
	out := new(MsgSetEncryptionKeyResponse)
	err := c.cc.Invoke(ctx, Msg_SetEncryptionKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetPqKey(ctx context.Context, in *MsgSetPqKey, opts ...grpc.CallOption) (*MsgSetPqKeyResponse, error) {
	out := new(MsgSetPqKeyResponse)
	err := c.cc.Invoke(ctx, Msg_SetPqKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateWalletProfile(ctx context.Context, in *MsgUpdateWalletProfile, opts ...grpc.CallOption) (*MsgUpdateWalletProfileResponse, error) {
	out := new(MsgUpdateWalletProfileResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateWalletProfile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetWalletPermissions(ctx context.Context, in *MsgSetWalletPermissions, opts ...grpc.CallOption) (*MsgSetWalletPermissionsResponse, error) {
	out := new(MsgSetWalletPermissionsResponse)
	err := c.cc.Invoke(ctx, Msg_SetWalletPermissions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LockWallet(ctx context.Context, in *MsgLockWallet, opts ...grpc.CallOption) (*MsgLockWalletResponse, error) {
	out := new(MsgLockWalletResponse)
	err := c.cc.Invoke(ctx, Msg_LockWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnlockWallet(ctx context.Context, in *MsgUnlockWallet, opts ...grpc.CallOption) (*MsgUnlockWalletResponse, error) {
	out := new(MsgUnlockWalletResponse)
	err := c.cc.Invoke(ctx, Msg_UnlockWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	RegisterWalletProfile(context.Context, *MsgRegisterWalletProfile) (*MsgRegisterWalletProfileResponse, error)
	SetEncryptionKey(context.Context, *MsgSetEncryptionKey) (*MsgSetEncryptionKeyResponse, error)
	SetPqKey(context.Context, *MsgSetPqKey) (*MsgSetPqKeyResponse, error)
	UpdateWalletProfile(context.Context, *MsgUpdateWalletProfile) (*MsgUpdateWalletProfileResponse, error)
	SetWalletPermissions(context.Context, *MsgSetWalletPermissions) (*MsgSetWalletPermissionsResponse, error)
	LockWallet(context.Context, *MsgLockWallet) (*MsgLockWalletResponse, error)
	UnlockWallet(context.Context, *MsgUnlockWallet) (*MsgUnlockWalletResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) RegisterWalletProfile(context.Context, *MsgRegisterWalletProfile) (*MsgRegisterWalletProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWalletProfile not implemented")
}
func (UnimplementedMsgServer) SetEncryptionKey(context.Context, *MsgSetEncryptionKey) (*MsgSetEncryptionKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetEncryptionKey not implemented")
}
func (UnimplementedMsgServer) SetPqKey(context.Context, *MsgSetPqKey) (*MsgSetPqKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPqKey not implemented")
}
func (UnimplementedMsgServer) UpdateWalletProfile(context.Context, *MsgUpdateWalletProfile) (*MsgUpdateWalletProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWalletProfile not implemented")
}
func (UnimplementedMsgServer) SetWalletPermissions(context.Context, *MsgSetWalletPermissions) (*MsgSetWalletPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWalletPermissions not implemented")
}
func (UnimplementedMsgServer) LockWallet(context.Context, *MsgLockWallet) (*MsgLockWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockWallet not implemented")
}
func (UnimplementedMsgServer) UnlockWallet(context.Context, *MsgUnlockWallet) (*MsgUnlockWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockWallet not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterWalletProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterWalletProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterWalletProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterWalletProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterWalletProfile(ctx, req.(*MsgRegisterWalletProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetEncryptionKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetEncryptionKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetEncryptionKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetEncryptionKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetEncryptionKey(ctx, req.(*MsgSetEncryptionKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetPqKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetPqKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetPqKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetPqKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetPqKey(ctx, req.(*MsgSetPqKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateWalletProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateWalletProfile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateWalletProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateWalletProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateWalletProfile(ctx, req.(*MsgUpdateWalletProfile))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetWalletPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetWalletPermissions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetWalletPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetWalletPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetWalletPermissions(ctx, req.(*MsgSetWalletPermissions))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LockWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLockWallet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LockWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_LockWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LockWallet(ctx, req.(*MsgLockWallet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnlockWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnlockWallet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnlockWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UnlockWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnlockWallet(ctx, req.(*MsgUnlockWallet))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qcb.qcbwalletproto.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterWalletProfile",
			Handler:    _Msg_RegisterWalletProfile_Handler,
		},
		{
			MethodName: "SetEncryptionKey",
			Handler:    _Msg_SetEncryptionKey_Handler,
		},
		{
			MethodName: "SetPqKey",
			Handler:    _Msg_SetPqKey_Handler,
		},
		{
			MethodName: "UpdateWalletProfile",
			Handler:    _Msg_UpdateWalletProfile_Handler,
		},
		{
			MethodName: "SetWalletPermissions",
			Handler:    _Msg_SetWalletPermissions_Handler,
		},
		{
			MethodName: "LockWallet",
			Handler:    _Msg_LockWallet_Handler,
		},
		{
			MethodName: "UnlockWallet",
			Handler:    _Msg_UnlockWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qcb/qcbwalletproto/tx.proto",
}
