// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qcb/qcbagent/agent.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Agent struct {
	Index        string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	NodeId       string `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AgentType    string `protobuf:"bytes,4,opt,name=agentType,proto3" json:"agentType,omitempty"`
	Owner        string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	DnaHash      string `protobuf:"bytes,6,opt,name=dnaHash,proto3" json:"dnaHash,omitempty"`
	Strength     uint64 `protobuf:"varint,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Agility      uint64 `protobuf:"varint,8,opt,name=agility,proto3" json:"agility,omitempty"`
	Stamina      uint64 `protobuf:"varint,9,opt,name=stamina,proto3" json:"stamina,omitempty"`
	Skill        uint64 `protobuf:"varint,10,opt,name=skill,proto3" json:"skill,omitempty"`
	Generation   uint64 `protobuf:"varint,11,opt,name=generation,proto3" json:"generation,omitempty"`
	TotalTrades  int32  `protobuf:"varint,12,opt,name=totalTrades,proto3" json:"totalTrades,omitempty"`
	Wins         int32  `protobuf:"varint,13,opt,name=wins,proto3" json:"wins,omitempty"`
	WinRateBps   int32  `protobuf:"varint,14,opt,name=winRateBps,proto3" json:"winRateBps,omitempty"`
	Experience   int32  `protobuf:"varint,15,opt,name=experience,proto3" json:"experience,omitempty"`
	Active       bool   `protobuf:"varint,16,opt,name=active,proto3" json:"active,omitempty"`
	GenesisBlock int32  `protobuf:"varint,17,opt,name=genesisBlock,proto3" json:"genesisBlock,omitempty"`
	ParentA      string `protobuf:"bytes,18,opt,name=parentA,proto3" json:"parentA,omitempty"`
	ParentB      string `protobuf:"bytes,19,opt,name=parentB,proto3" json:"parentB,omitempty"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab0664d54e88f9f6, []int{0}
}
func (m *Agent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return m.Size()
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Agent) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetAgentType() string {
	if m != nil {
		return m.AgentType
	}
	return ""
}

func (m *Agent) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Agent) GetDnaHash() string {
	if m != nil {
		return m.DnaHash
	}
	return ""
}

func (m *Agent) GetStrength() uint64 {
	if m != nil {
		return m.Strength
	}
	return 0
}

func (m *Agent) GetAgility() uint64 {
	if m != nil {
		return m.Agility
	}
	return 0
}

func (m *Agent) GetStamina() uint64 {
	if m != nil {
		return m.Stamina
	}
	return 0
}

func (m *Agent) GetSkill() uint64 {
	if m != nil {
		return m.Skill
	}
	return 0
}

func (m *Agent) GetGeneration() uint64 {
	if m != nil {
		return m.Generation
	}
	return 0
}

func (m *Agent) GetTotalTrades() int32 {
	if m != nil {
		return m.TotalTrades
	}
	return 0
}

func (m *Agent) GetWins() int32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

func (m *Agent) GetWinRateBps() int32 {
	if m != nil {
		return m.WinRateBps
	}
	return 0
}

func (m *Agent) GetExperience() int32 {
	if m != nil {
		return m.Experience
	}
	return 0
}

func (m *Agent) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Agent) GetGenesisBlock() int32 {
	if m != nil {
		return m.GenesisBlock
	}
	return 0
}

func (m *Agent) GetParentA() string {
	if m != nil {
		return m.ParentA
	}
	return ""
}

func (m *Agent) GetParentB() string {
	if m != nil {
		return m.ParentB
	}
	return ""
}

func init() {
	proto.RegisterType((*Agent)(nil), "qcb.qcbagent.Agent")
}

func init() { proto.RegisterFile("qcb/qcbagent/agent.proto", fileDescriptor_ab0664d54e88f9f6) }

var fileDescriptor_ab0664d54e88f9f6 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xbd, 0x0e, 0xda, 0x30,
	0x10, 0xc7, 0x71, 0x9b, 0xf0, 0x61, 0xe8, 0x97, 0x8b, 0xaa, 0x53, 0x55, 0x45, 0x11, 0x53, 0x26,
	0x18, 0xfa, 0x04, 0x64, 0x6a, 0xd7, 0x88, 0xa9, 0x9b, 0x93, 0x9c, 0x82, 0x45, 0x70, 0x42, 0x6c,
	0x15, 0x98, 0xfb, 0x02, 0x7d, 0xac, 0x8e, 0x8c, 0x1d, 0x2b, 0x78, 0x91, 0xca, 0x97, 0xd0, 0xa4,
	0x4b, 0x74, 0xff, 0xdf, 0x4f, 0x77, 0xb1, 0x4e, 0xc7, 0xe1, 0x94, 0xa5, 0x9b, 0x53, 0x96, 0xca,
	0x02, 0xb5, 0xdd, 0xd0, 0x77, 0x5d, 0x37, 0x95, 0xad, 0xc4, 0xe2, 0x94, 0xa5, 0xeb, 0xa7, 0x59,
	0xfd, 0xf0, 0xb8, 0xbf, 0x75, 0x95, 0x58, 0x72, 0x5f, 0xe9, 0x1c, 0x2f, 0xc0, 0x42, 0x16, 0xcd,
	0x92, 0x36, 0x88, 0x0f, 0x7c, 0xac, 0xab, 0x1c, 0xbf, 0xe6, 0xf0, 0x82, 0x70, 0x97, 0x84, 0xe0,
	0x9e, 0x96, 0x47, 0x84, 0x97, 0x44, 0xa9, 0x16, 0x9f, 0xf8, 0x8c, 0x86, 0xee, 0xae, 0x35, 0x82,
	0x47, 0xa2, 0x07, 0x6e, 0x7e, 0x75, 0xd6, 0xd8, 0x80, 0xdf, 0xce, 0xa7, 0x20, 0x80, 0x4f, 0x72,
	0x2d, 0xbf, 0x48, 0xb3, 0x87, 0x31, 0xf1, 0x67, 0x14, 0x1f, 0xf9, 0xd4, 0xd8, 0x06, 0x75, 0x61,
	0xf7, 0x30, 0x09, 0x59, 0xe4, 0x25, 0xff, 0xb2, 0xeb, 0x92, 0x85, 0x2a, 0x95, 0xbd, 0xc2, 0x94,
	0xd4, 0x33, 0x3a, 0x63, 0xac, 0x3c, 0x2a, 0x2d, 0x61, 0xd6, 0x9a, 0x2e, 0xba, 0xff, 0x9b, 0x83,
	0x2a, 0x4b, 0xe0, 0xc4, 0xdb, 0x20, 0x02, 0xce, 0x0b, 0xd4, 0xd8, 0x48, 0xab, 0x2a, 0x0d, 0x73,
	0x52, 0x03, 0x22, 0x42, 0x3e, 0xb7, 0x95, 0x95, 0xe5, 0xae, 0x91, 0x39, 0x1a, 0x58, 0x84, 0x2c,
	0xf2, 0x93, 0x21, 0x72, 0x9b, 0x38, 0x2b, 0x6d, 0xe0, 0x15, 0x29, 0xaa, 0xdd, 0xd4, 0xb3, 0xd2,
	0x89, 0xb4, 0x18, 0xd7, 0x06, 0x5e, 0x93, 0x19, 0x10, 0xe7, 0xf1, 0x52, 0x63, 0xa3, 0x50, 0x67,
	0x08, 0x6f, 0x5a, 0xdf, 0x13, 0xb7, 0x75, 0x99, 0x59, 0xf5, 0x1d, 0xe1, 0x6d, 0xc8, 0xa2, 0x69,
	0xd2, 0x25, 0xb1, 0xe2, 0x0b, 0xf7, 0x36, 0xa3, 0x4c, 0x5c, 0x56, 0xd9, 0x01, 0xde, 0x51, 0xe7,
	0x7f, 0xcc, 0x6d, 0xa0, 0x96, 0x0d, 0x6a, 0xbb, 0x05, 0xd1, 0x6e, 0xb4, 0x8b, 0xbd, 0x89, 0xe1,
	0xfd, 0xd0, 0xc4, 0xf1, 0xfa, 0xd7, 0x3d, 0x60, 0xb7, 0x7b, 0xc0, 0xfe, 0xdc, 0x03, 0xf6, 0xf3,
	0x11, 0x8c, 0x6e, 0x8f, 0x60, 0xf4, 0xfb, 0x11, 0x8c, 0xbe, 0x2d, 0xdd, 0x1d, 0x5d, 0xfa, 0x4b,
	0xb2, 0xd7, 0x1a, 0x4d, 0x3a, 0xa6, 0x53, 0xfa, 0xfc, 0x37, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x35,
	0x5a, 0x4a, 0x66, 0x02, 0x00, 0x00,
}

func (m *Agent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Agent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Agent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ParentB) > 0 {
		i -= len(m.ParentB)
		copy(dAtA[i:], m.ParentB)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.ParentB)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x9a
	}
	if len(m.ParentA) > 0 {
		i -= len(m.ParentA)
		copy(dAtA[i:], m.ParentA)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.ParentA)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if m.GenesisBlock != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.GenesisBlock))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if m.Experience != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.Experience))
		i--
		dAtA[i] = 0x78
	}
	if m.WinRateBps != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.WinRateBps))
		i--
		dAtA[i] = 0x70
	}
	if m.Wins != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.Wins))
		i--
		dAtA[i] = 0x68
	}
	if m.TotalTrades != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.TotalTrades))
		i--
		dAtA[i] = 0x60
	}
	if m.Generation != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.Generation))
		i--
		dAtA[i] = 0x58
	}
	if m.Skill != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.Skill))
		i--
		dAtA[i] = 0x50
	}
	if m.Stamina != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.Stamina))
		i--
		dAtA[i] = 0x48
	}
	if m.Agility != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.Agility))
		i--
		dAtA[i] = 0x40
	}
	if m.Strength != 0 {
		i = encodeVarintAgent(dAtA, i, uint64(m.Strength))
		i--
		dAtA[i] = 0x38
	}
	if len(m.DnaHash) > 0 {
		i -= len(m.DnaHash)
		copy(dAtA[i:], m.DnaHash)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.DnaHash)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AgentType) > 0 {
		i -= len(m.AgentType)
		copy(dAtA[i:], m.AgentType)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.AgentType)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NodeId) > 0 {
		i -= len(m.NodeId)
		copy(dAtA[i:], m.NodeId)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.NodeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintAgent(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAgent(dAtA []byte, offset int, v uint64) int {
	offset -= sovAgent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Agent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovAgent(uint64(l))
	}
	l = len(m.NodeId)
	if l > 0 {
		n += 1 + l + sovAgent(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAgent(uint64(l))
	}
	l = len(m.AgentType)
	if l > 0 {
		n += 1 + l + sovAgent(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovAgent(uint64(l))
	}
	l = len(m.DnaHash)
	if l > 0 {
		n += 1 + l + sovAgent(uint64(l))
	}
	if m.Strength != 0 {
		n += 1 + sovAgent(uint64(m.Strength))
	}
	if m.Agility != 0 {
		n += 1 + sovAgent(uint64(m.Agility))
	}
	if m.Stamina != 0 {
		n += 1 + sovAgent(uint64(m.Stamina))
	}
	if m.Skill != 0 {
		n += 1 + sovAgent(uint64(m.Skill))
	}
	if m.Generation != 0 {
		n += 1 + sovAgent(uint64(m.Generation))
	}
	if m.TotalTrades != 0 {
		n += 1 + sovAgent(uint64(m.TotalTrades))
	}
	if m.Wins != 0 {
		n += 1 + sovAgent(uint64(m.Wins))
	}
	if m.WinRateBps != 0 {
		n += 1 + sovAgent(uint64(m.WinRateBps))
	}
	if m.Experience != 0 {
		n += 1 + sovAgent(uint64(m.Experience))
	}
	if m.Active {
		n += 3
	}
	if m.GenesisBlock != 0 {
		n += 2 + sovAgent(uint64(m.GenesisBlock))
	}
	l = len(m.ParentA)
	if l > 0 {
		n += 2 + l + sovAgent(uint64(l))
	}
	l = len(m.ParentB)
	if l > 0 {
		n += 2 + l + sovAgent(uint64(l))
	}
	return n
}

func sovAgent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAgent(x uint64) (n int) {
	return sovAgent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Agent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAgent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Agent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Agent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DnaHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DnaHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strength", wireType)
			}
			m.Strength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Strength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Agility", wireType)
			}
			m.Agility = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Agility |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stamina", wireType)
			}
			m.Stamina = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stamina |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skill", wireType)
			}
			m.Skill = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Skill |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Generation", wireType)
			}
			m.Generation = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Generation |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTrades", wireType)
			}
			m.TotalTrades = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalTrades |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wins", wireType)
			}
			m.Wins = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Wins |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinRateBps", wireType)
			}
			m.WinRateBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WinRateBps |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
			}
			m.Experience = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Experience |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisBlock", wireType)
			}
			m.GenesisBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenesisBlock |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentA", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentA = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentB", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAgent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAgent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentB = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAgent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAgent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAgent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAgent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAgent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAgent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAgent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAgent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAgent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAgent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAgent = fmt.Errorf("proto: unexpected end of group")
)
