// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oan/oanprotocol/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1ef95d25b79ca3, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1ef95d25b79ca3, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryAddressStatusRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAddressStatusRequest) Reset()         { *m = QueryAddressStatusRequest{} }
func (m *QueryAddressStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAddressStatusRequest) ProtoMessage()    {}
func (*QueryAddressStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1ef95d25b79ca3, []int{2}
}
func (m *QueryAddressStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddressStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddressStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddressStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddressStatusRequest.Merge(m, src)
}
func (m *QueryAddressStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddressStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddressStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddressStatusRequest proto.InternalMessageInfo

func (m *QueryAddressStatusRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAddressStatusResponse struct {
	Tier          string `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"`
	DailyReceived string `protobuf:"bytes,2,opt,name=dailyReceived,proto3" json:"dailyReceived,omitempty"`
	DailyLimit    string `protobuf:"bytes,3,opt,name=dailyLimit,proto3" json:"dailyLimit,omitempty"`
	MaxBalance    string `protobuf:"bytes,4,opt,name=maxBalance,proto3" json:"maxBalance,omitempty"`
}

func (m *QueryAddressStatusResponse) Reset()         { *m = QueryAddressStatusResponse{} }
func (m *QueryAddressStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAddressStatusResponse) ProtoMessage()    {}
func (*QueryAddressStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1ef95d25b79ca3, []int{3}
}
func (m *QueryAddressStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddressStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddressStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddressStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddressStatusResponse.Merge(m, src)
}
func (m *QueryAddressStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddressStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddressStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddressStatusResponse proto.InternalMessageInfo

func (m *QueryAddressStatusResponse) GetTier() string {
	if m != nil {
		return m.Tier
	}
	return ""
}

func (m *QueryAddressStatusResponse) GetDailyReceived() string {
	if m != nil {
		return m.DailyReceived
	}
	return ""
}

func (m *QueryAddressStatusResponse) GetDailyLimit() string {
	if m != nil {
		return m.DailyLimit
	}
	return ""
}

func (m *QueryAddressStatusResponse) GetMaxBalance() string {
	if m != nil {
		return m.MaxBalance
	}
	return ""
}

type QueryProtocolParamsRequest struct {
}

func (m *QueryProtocolParamsRequest) Reset()         { *m = QueryProtocolParamsRequest{} }
func (m *QueryProtocolParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProtocolParamsRequest) ProtoMessage()    {}
func (*QueryProtocolParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1ef95d25b79ca3, []int{4}
}
func (m *QueryProtocolParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProtocolParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProtocolParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProtocolParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProtocolParamsRequest.Merge(m, src)
}
func (m *QueryProtocolParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryProtocolParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProtocolParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProtocolParamsRequest proto.InternalMessageInfo

type QueryProtocolParamsResponse struct {
	Params string `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
}

func (m *QueryProtocolParamsResponse) Reset()         { *m = QueryProtocolParamsResponse{} }
func (m *QueryProtocolParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProtocolParamsResponse) ProtoMessage()    {}
func (*QueryProtocolParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a1ef95d25b79ca3, []int{5}
}
func (m *QueryProtocolParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryProtocolParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryProtocolParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryProtocolParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProtocolParamsResponse.Merge(m, src)
}
func (m *QueryProtocolParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryProtocolParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProtocolParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProtocolParamsResponse proto.InternalMessageInfo

func (m *QueryProtocolParamsResponse) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "oan.oanprotocol.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "oan.oanprotocol.QueryParamsResponse")
	proto.RegisterType((*QueryAddressStatusRequest)(nil), "oan.oanprotocol.QueryAddressStatusRequest")
	proto.RegisterType((*QueryAddressStatusResponse)(nil), "oan.oanprotocol.QueryAddressStatusResponse")
	proto.RegisterType((*QueryProtocolParamsRequest)(nil), "oan.oanprotocol.QueryProtocolParamsRequest")
	proto.RegisterType((*QueryProtocolParamsResponse)(nil), "oan.oanprotocol.QueryProtocolParamsResponse")
}

func init() { proto.RegisterFile("oan/oanprotocol/query.proto", fileDescriptor_3a1ef95d25b79ca3) }

var fileDescriptor_3a1ef95d25b79ca3 = []byte{
	// 491 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0xb4, 0x35, 0x92, 0x91, 0x2a, 0x8e, 0xc5, 0x6c, 0xb7, 0x65, 0x5b, 0xd6, 0x1e, 0x6a,
	0x2a, 0x19, 0x52, 0xe9, 0xc5, 0x9b, 0x39, 0x7b, 0x68, 0xe3, 0xcd, 0x4b, 0x79, 0x49, 0x86, 0x65,
	0x20, 0x3b, 0xb3, 0xdd, 0x99, 0x94, 0x06, 0xf1, 0xe2, 0x2f, 0x10, 0x44, 0x2f, 0xfe, 0x01, 0x8f,
	0x82, 0x7f, 0xa2, 0xc7, 0x82, 0x17, 0x4f, 0x22, 0x89, 0xe0, 0xdf, 0x90, 0xbc, 0x99, 0x60, 0xb7,
	0xbb, 0x4a, 0x2e, 0xcb, 0x7b, 0xdf, 0x7b, 0xdf, 0x7b, 0xdf, 0x7c, 0x6f, 0xe9, 0x96, 0x06, 0xc5,
	0x35, 0xa8, 0x2c, 0xd7, 0x56, 0x0f, 0xf4, 0x88, 0x9f, 0x8d, 0x45, 0x3e, 0x69, 0x63, 0xca, 0xee,
	0x69, 0x50, 0xed, 0x6b, 0xc5, 0xf0, 0x3e, 0xa4, 0x52, 0x69, 0x8e, 0x5f, 0xd7, 0x13, 0x6e, 0x24,
	0x3a, 0xd1, 0x18, 0xf2, 0x79, 0xe4, 0xd1, 0xed, 0x44, 0xeb, 0x64, 0x24, 0x38, 0x64, 0x92, 0x83,
	0x52, 0xda, 0x82, 0x95, 0x5a, 0x19, 0x5f, 0x6d, 0x0d, 0xb4, 0x49, 0xb5, 0xe1, 0x7d, 0x30, 0xc2,
	0x2d, 0xe4, 0xe7, 0x9d, 0xbe, 0xb0, 0xd0, 0xe1, 0x19, 0x24, 0x52, 0x61, 0xf3, 0x62, 0xd2, 0x4d,
	0x81, 0x19, 0xe4, 0x90, 0xfa, 0x49, 0xf1, 0x06, 0x65, 0x27, 0x73, 0xfe, 0x31, 0x82, 0x3d, 0x71,
	0x36, 0x16, 0xc6, 0xc6, 0x27, 0xf4, 0x41, 0x01, 0x35, 0x99, 0x56, 0x46, 0xb0, 0x67, 0xb4, 0xee,
	0xc8, 0x01, 0xd9, 0x25, 0xfb, 0x77, 0x0e, 0x9b, 0xed, 0x1b, 0xef, 0x6b, 0x3b, 0x42, 0xb7, 0x71,
	0xf9, 0x63, 0xa7, 0xf6, 0xf9, 0xf7, 0x97, 0x16, 0xe9, 0x79, 0x46, 0x7c, 0x44, 0x37, 0x71, 0xe4,
	0xf3, 0xe1, 0x30, 0x17, 0xc6, 0xbc, 0xb4, 0x60, 0xc7, 0x8b, 0x7d, 0x2c, 0xa0, 0xb7, 0xc1, 0xe1,
	0x38, 0xb9, 0xd1, 0x5b, 0xa4, 0xf1, 0x47, 0x42, 0xc3, 0x2a, 0x9e, 0x57, 0xc4, 0xe8, 0x9a, 0x95,
	0x22, 0xf7, 0x2c, 0x8c, 0xd9, 0x1e, 0x5d, 0x1f, 0x82, 0x1c, 0x4d, 0x7a, 0x62, 0x20, 0xe4, 0xb9,
	0x18, 0x06, 0x2b, 0x58, 0x2c, 0x82, 0x2c, 0xa2, 0x14, 0x81, 0x17, 0x32, 0x95, 0x36, 0x58, 0xc5,
	0x96, 0x6b, 0xc8, 0xbc, 0x9e, 0xc2, 0x45, 0x17, 0x46, 0xa0, 0x06, 0x22, 0x58, 0x73, 0xf5, 0xbf,
	0x48, 0xbc, 0xed, 0x75, 0x1d, 0xfb, 0xa7, 0x17, 0x0d, 0x3c, 0xa2, 0x5b, 0x95, 0x55, 0x2f, 0xfb,
	0x61, 0xc1, 0xc8, 0xc6, 0xc2, 0xa4, 0xc3, 0xaf, 0xab, 0xf4, 0x16, 0xf2, 0x98, 0xa5, 0x75, 0xc7,
	0x61, 0x8f, 0x4a, 0x26, 0x97, 0x0f, 0x16, 0xee, 0xfd, 0xbf, 0xc9, 0xad, 0x8d, 0x77, 0xde, 0x7e,
	0xfb, 0xf5, 0x7e, 0x65, 0x93, 0x35, 0x79, 0xf5, 0x3f, 0xc1, 0x3e, 0x11, 0xba, 0x5e, 0x30, 0x9a,
	0xb5, 0xaa, 0x07, 0x57, 0x5d, 0x31, 0x3c, 0x58, 0xaa, 0xd7, 0x6b, 0xe9, 0xa0, 0x96, 0x03, 0xf6,
	0xb8, 0xa4, 0xc5, 0x9f, 0xfe, 0xd4, 0x20, 0x81, 0xbf, 0xf6, 0xf9, 0x1b, 0xf6, 0x81, 0xd0, 0xbb,
	0x45, 0x43, 0xd9, 0x3f, 0x56, 0x56, 0x1e, 0x25, 0x7c, 0xb2, 0x5c, 0xb3, 0x17, 0xb8, 0x8f, 0x02,
	0x63, 0xb6, 0x5b, 0x36, 0xcb, 0x07, 0xa7, 0xce, 0xb5, 0x6e, 0xe7, 0x72, 0x1a, 0x91, 0xab, 0x69,
	0x44, 0x7e, 0x4e, 0x23, 0xf2, 0x6e, 0x16, 0xd5, 0xae, 0x66, 0x51, 0xed, 0xfb, 0x2c, 0xaa, 0xbd,
	0x6a, 0xce, 0xa9, 0x17, 0x05, 0xb2, 0x9d, 0x64, 0xc2, 0xf4, 0xeb, 0x98, 0x3f, 0xfd, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x3e, 0x2b, 0x77, 0xb6, 0x3e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of AddressStatus items.
	AddressStatus(ctx context.Context, in *QueryAddressStatusRequest, opts ...grpc.CallOption) (*QueryAddressStatusResponse, error)
	// Queries a list of ProtocolParams items.
	ProtocolParams(ctx context.Context, in *QueryProtocolParamsRequest, opts ...grpc.CallOption) (*QueryProtocolParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/oan.oanprotocol.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AddressStatus(ctx context.Context, in *QueryAddressStatusRequest, opts ...grpc.CallOption) (*QueryAddressStatusResponse, error) {
	out := new(QueryAddressStatusResponse)
	err := c.cc.Invoke(ctx, "/oan.oanprotocol.Query/AddressStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ProtocolParams(ctx context.Context, in *QueryProtocolParamsRequest, opts ...grpc.CallOption) (*QueryProtocolParamsResponse, error) {
	out := new(QueryProtocolParamsResponse)
	err := c.cc.Invoke(ctx, "/oan.oanprotocol.Query/ProtocolParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of AddressStatus items.
	AddressStatus(context.Context, *QueryAddressStatusRequest) (*QueryAddressStatusResponse, error)
	// Queries a list of ProtocolParams items.
	ProtocolParams(context.Context, *QueryProtocolParamsRequest) (*QueryProtocolParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AddressStatus(ctx context.Context, req *QueryAddressStatusRequest) (*QueryAddressStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressStatus not implemented")
}
func (*UnimplementedQueryServer) ProtocolParams(ctx context.Context, req *QueryProtocolParamsRequest) (*QueryProtocolParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProtocolParams not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oan.oanprotocol.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AddressStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAddressStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AddressStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oan.oanprotocol.Query/AddressStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AddressStatus(ctx, req.(*QueryAddressStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ProtocolParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProtocolParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ProtocolParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oan.oanprotocol.Query/ProtocolParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ProtocolParams(ctx, req.(*QueryProtocolParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oan.oanprotocol.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AddressStatus",
			Handler:    _Query_AddressStatus_Handler,
		},
		{
			MethodName: "ProtocolParams",
			Handler:    _Query_ProtocolParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oan/oanprotocol/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAddressStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddressStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddressStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAddressStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddressStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddressStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MaxBalance) > 0 {
		i -= len(m.MaxBalance)
		copy(dAtA[i:], m.MaxBalance)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MaxBalance)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DailyLimit) > 0 {
		i -= len(m.DailyLimit)
		copy(dAtA[i:], m.DailyLimit)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DailyLimit)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DailyReceived) > 0 {
		i -= len(m.DailyReceived)
		copy(dAtA[i:], m.DailyReceived)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DailyReceived)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tier) > 0 {
		i -= len(m.Tier)
		copy(dAtA[i:], m.Tier)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Tier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryProtocolParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProtocolParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProtocolParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryProtocolParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryProtocolParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryProtocolParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Params) > 0 {
		i -= len(m.Params)
		copy(dAtA[i:], m.Params)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Params)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAddressStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAddressStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Tier)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DailyReceived)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DailyLimit)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.MaxBalance)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryProtocolParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryProtocolParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Params)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAddressStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddressStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddressStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAddressStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddressStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddressStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyReceived", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DailyReceived = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyLimit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DailyLimit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxBalance = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProtocolParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProtocolParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProtocolParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryProtocolParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryProtocolParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryProtocolParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
