// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package qcbagent

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Agent              protoreflect.MessageDescriptor
	fd_Agent_index        protoreflect.FieldDescriptor
	fd_Agent_nodeId       protoreflect.FieldDescriptor
	fd_Agent_name         protoreflect.FieldDescriptor
	fd_Agent_agentType    protoreflect.FieldDescriptor
	fd_Agent_owner        protoreflect.FieldDescriptor
	fd_Agent_dnaHash      protoreflect.FieldDescriptor
	fd_Agent_strength     protoreflect.FieldDescriptor
	fd_Agent_agility      protoreflect.FieldDescriptor
	fd_Agent_stamina      protoreflect.FieldDescriptor
	fd_Agent_skill        protoreflect.FieldDescriptor
	fd_Agent_generation   protoreflect.FieldDescriptor
	fd_Agent_totalTrades  protoreflect.FieldDescriptor
	fd_Agent_wins         protoreflect.FieldDescriptor
	fd_Agent_winRateBps   protoreflect.FieldDescriptor
	fd_Agent_experience   protoreflect.FieldDescriptor
	fd_Agent_active       protoreflect.FieldDescriptor
	fd_Agent_genesisBlock protoreflect.FieldDescriptor
	fd_Agent_parentA      protoreflect.FieldDescriptor
	fd_Agent_parentB      protoreflect.FieldDescriptor
)

func init() {
	file_qcb_qcbagent_agent_proto_init()
	md_Agent = File_qcb_qcbagent_agent_proto.Messages().ByName("Agent")
	fd_Agent_index = md_Agent.Fields().ByName("index")
	fd_Agent_nodeId = md_Agent.Fields().ByName("nodeId")
	fd_Agent_name = md_Agent.Fields().ByName("name")
	fd_Agent_agentType = md_Agent.Fields().ByName("agentType")
	fd_Agent_owner = md_Agent.Fields().ByName("owner")
	fd_Agent_dnaHash = md_Agent.Fields().ByName("dnaHash")
	fd_Agent_strength = md_Agent.Fields().ByName("strength")
	fd_Agent_agility = md_Agent.Fields().ByName("agility")
	fd_Agent_stamina = md_Agent.Fields().ByName("stamina")
	fd_Agent_skill = md_Agent.Fields().ByName("skill")
	fd_Agent_generation = md_Agent.Fields().ByName("generation")
	fd_Agent_totalTrades = md_Agent.Fields().ByName("totalTrades")
	fd_Agent_wins = md_Agent.Fields().ByName("wins")
	fd_Agent_winRateBps = md_Agent.Fields().ByName("winRateBps")
	fd_Agent_experience = md_Agent.Fields().ByName("experience")
	fd_Agent_active = md_Agent.Fields().ByName("active")
	fd_Agent_genesisBlock = md_Agent.Fields().ByName("genesisBlock")
	fd_Agent_parentA = md_Agent.Fields().ByName("parentA")
	fd_Agent_parentB = md_Agent.Fields().ByName("parentB")
}

var _ protoreflect.Message = (*fastReflection_Agent)(nil)

type fastReflection_Agent Agent

func (x *Agent) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Agent)(x)
}

func (x *Agent) slowProtoReflect() protoreflect.Message {
	mi := &file_qcb_qcbagent_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Agent_messageType fastReflection_Agent_messageType
var _ protoreflect.MessageType = fastReflection_Agent_messageType{}

type fastReflection_Agent_messageType struct{}

func (x fastReflection_Agent_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Agent)(nil)
}
func (x fastReflection_Agent_messageType) New() protoreflect.Message {
	return new(fastReflection_Agent)
}
func (x fastReflection_Agent_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Agent
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Agent) Descriptor() protoreflect.MessageDescriptor {
	return md_Agent
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Agent) Type() protoreflect.MessageType {
	return _fastReflection_Agent_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Agent) New() protoreflect.Message {
	return new(fastReflection_Agent)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Agent) Interface() protoreflect.ProtoMessage {
	return (*Agent)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Agent) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_Agent_index, value) {
			return
		}
	}
	if x.NodeId != "" {
		value := protoreflect.ValueOfString(x.NodeId)
		if !f(fd_Agent_nodeId, value) {
			return
		}
	}
	if x.Name != "" {
		value := protoreflect.ValueOfString(x.Name)
		if !f(fd_Agent_name, value) {
			return
		}
	}
	if x.AgentType != "" {
		value := protoreflect.ValueOfString(x.AgentType)
		if !f(fd_Agent_agentType, value) {
			return
		}
	}
	if x.Owner != "" {
		value := protoreflect.ValueOfString(x.Owner)
		if !f(fd_Agent_owner, value) {
			return
		}
	}
	if x.DnaHash != "" {
		value := protoreflect.ValueOfString(x.DnaHash)
		if !f(fd_Agent_dnaHash, value) {
			return
		}
	}
	if x.Strength != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Strength)
		if !f(fd_Agent_strength, value) {
			return
		}
	}
	if x.Agility != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Agility)
		if !f(fd_Agent_agility, value) {
			return
		}
	}
	if x.Stamina != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Stamina)
		if !f(fd_Agent_stamina, value) {
			return
		}
	}
	if x.Skill != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Skill)
		if !f(fd_Agent_skill, value) {
			return
		}
	}
	if x.Generation != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Generation)
		if !f(fd_Agent_generation, value) {
			return
		}
	}
	if x.TotalTrades != int32(0) {
		value := protoreflect.ValueOfInt32(x.TotalTrades)
		if !f(fd_Agent_totalTrades, value) {
			return
		}
	}
	if x.Wins != int32(0) {
		value := protoreflect.ValueOfInt32(x.Wins)
		if !f(fd_Agent_wins, value) {
			return
		}
	}
	if x.WinRateBps != int32(0) {
		value := protoreflect.ValueOfInt32(x.WinRateBps)
		if !f(fd_Agent_winRateBps, value) {
			return
		}
	}
	if x.Experience != int32(0) {
		value := protoreflect.ValueOfInt32(x.Experience)
		if !f(fd_Agent_experience, value) {
			return
		}
	}
	if x.Active != false {
		value := protoreflect.ValueOfBool(x.Active)
		if !f(fd_Agent_active, value) {
			return
		}
	}
	if x.GenesisBlock != int32(0) {
		value := protoreflect.ValueOfInt32(x.GenesisBlock)
		if !f(fd_Agent_genesisBlock, value) {
			return
		}
	}
	if x.ParentA != "" {
		value := protoreflect.ValueOfString(x.ParentA)
		if !f(fd_Agent_parentA, value) {
			return
		}
	}
	if x.ParentB != "" {
		value := protoreflect.ValueOfString(x.ParentB)
		if !f(fd_Agent_parentB, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Agent) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "qcb.qcbagent.Agent.index":
		return x.Index != ""
	case "qcb.qcbagent.Agent.nodeId":
		return x.NodeId != ""
	case "qcb.qcbagent.Agent.name":
		return x.Name != ""
	case "qcb.qcbagent.Agent.agentType":
		return x.AgentType != ""
	case "qcb.qcbagent.Agent.owner":
		return x.Owner != ""
	case "qcb.qcbagent.Agent.dnaHash":
		return x.DnaHash != ""
	case "qcb.qcbagent.Agent.strength":
		return x.Strength != uint64(0)
	case "qcb.qcbagent.Agent.agility":
		return x.Agility != uint64(0)
	case "qcb.qcbagent.Agent.stamina":
		return x.Stamina != uint64(0)
	case "qcb.qcbagent.Agent.skill":
		return x.Skill != uint64(0)
	case "qcb.qcbagent.Agent.generation":
		return x.Generation != uint64(0)
	case "qcb.qcbagent.Agent.totalTrades":
		return x.TotalTrades != int32(0)
	case "qcb.qcbagent.Agent.wins":
		return x.Wins != int32(0)
	case "qcb.qcbagent.Agent.winRateBps":
		return x.WinRateBps != int32(0)
	case "qcb.qcbagent.Agent.experience":
		return x.Experience != int32(0)
	case "qcb.qcbagent.Agent.active":
		return x.Active != false
	case "qcb.qcbagent.Agent.genesisBlock":
		return x.GenesisBlock != int32(0)
	case "qcb.qcbagent.Agent.parentA":
		return x.ParentA != ""
	case "qcb.qcbagent.Agent.parentB":
		return x.ParentB != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbagent.Agent"))
		}
		panic(fmt.Errorf("message qcb.qcbagent.Agent does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agent) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "qcb.qcbagent.Agent.index":
		x.Index = ""
	case "qcb.qcbagent.Agent.nodeId":
		x.NodeId = ""
	case "qcb.qcbagent.Agent.name":
		x.Name = ""
	case "qcb.qcbagent.Agent.agentType":
		x.AgentType = ""
	case "qcb.qcbagent.Agent.owner":
		x.Owner = ""
	case "qcb.qcbagent.Agent.dnaHash":
		x.DnaHash = ""
	case "qcb.qcbagent.Agent.strength":
		x.Strength = uint64(0)
	case "qcb.qcbagent.Agent.agility":
		x.Agility = uint64(0)
	case "qcb.qcbagent.Agent.stamina":
		x.Stamina = uint64(0)
	case "qcb.qcbagent.Agent.skill":
		x.Skill = uint64(0)
	case "qcb.qcbagent.Agent.generation":
		x.Generation = uint64(0)
	case "qcb.qcbagent.Agent.totalTrades":
		x.TotalTrades = int32(0)
	case "qcb.qcbagent.Agent.wins":
		x.Wins = int32(0)
	case "qcb.qcbagent.Agent.winRateBps":
		x.WinRateBps = int32(0)
	case "qcb.qcbagent.Agent.experience":
		x.Experience = int32(0)
	case "qcb.qcbagent.Agent.active":
		x.Active = false
	case "qcb.qcbagent.Agent.genesisBlock":
		x.GenesisBlock = int32(0)
	case "qcb.qcbagent.Agent.parentA":
		x.ParentA = ""
	case "qcb.qcbagent.Agent.parentB":
		x.ParentB = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbagent.Agent"))
		}
		panic(fmt.Errorf("message qcb.qcbagent.Agent does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Agent) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "qcb.qcbagent.Agent.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "qcb.qcbagent.Agent.nodeId":
		value := x.NodeId
		return protoreflect.ValueOfString(value)
	case "qcb.qcbagent.Agent.name":
		value := x.Name
		return protoreflect.ValueOfString(value)
	case "qcb.qcbagent.Agent.agentType":
		value := x.AgentType
		return protoreflect.ValueOfString(value)
	case "qcb.qcbagent.Agent.owner":
		value := x.Owner
		return protoreflect.ValueOfString(value)
	case "qcb.qcbagent.Agent.dnaHash":
		value := x.DnaHash
		return protoreflect.ValueOfString(value)
	case "qcb.qcbagent.Agent.strength":
		value := x.Strength
		return protoreflect.ValueOfUint64(value)
	case "qcb.qcbagent.Agent.agility":
		value := x.Agility
		return protoreflect.ValueOfUint64(value)
	case "qcb.qcbagent.Agent.stamina":
		value := x.Stamina
		return protoreflect.ValueOfUint64(value)
	case "qcb.qcbagent.Agent.skill":
		value := x.Skill
		return protoreflect.ValueOfUint64(value)
	case "qcb.qcbagent.Agent.generation":
		value := x.Generation
		return protoreflect.ValueOfUint64(value)
	case "qcb.qcbagent.Agent.totalTrades":
		value := x.TotalTrades
		return protoreflect.ValueOfInt32(value)
	case "qcb.qcbagent.Agent.wins":
		value := x.Wins
		return protoreflect.ValueOfInt32(value)
	case "qcb.qcbagent.Agent.winRateBps":
		value := x.WinRateBps
		return protoreflect.ValueOfInt32(value)
	case "qcb.qcbagent.Agent.experience":
		value := x.Experience
		return protoreflect.ValueOfInt32(value)
	case "qcb.qcbagent.Agent.active":
		value := x.Active
		return protoreflect.ValueOfBool(value)
	case "qcb.qcbagent.Agent.genesisBlock":
		value := x.GenesisBlock
		return protoreflect.ValueOfInt32(value)
	case "qcb.qcbagent.Agent.parentA":
		value := x.ParentA
		return protoreflect.ValueOfString(value)
	case "qcb.qcbagent.Agent.parentB":
		value := x.ParentB
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbagent.Agent"))
		}
		panic(fmt.Errorf("message qcb.qcbagent.Agent does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agent) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "qcb.qcbagent.Agent.index":
		x.Index = value.Interface().(string)
	case "qcb.qcbagent.Agent.nodeId":
		x.NodeId = value.Interface().(string)
	case "qcb.qcbagent.Agent.name":
		x.Name = value.Interface().(string)
	case "qcb.qcbagent.Agent.agentType":
		x.AgentType = value.Interface().(string)
	case "qcb.qcbagent.Agent.owner":
		x.Owner = value.Interface().(string)
	case "qcb.qcbagent.Agent.dnaHash":
		x.DnaHash = value.Interface().(string)
	case "qcb.qcbagent.Agent.strength":
		x.Strength = value.Uint()
	case "qcb.qcbagent.Agent.agility":
		x.Agility = value.Uint()
	case "qcb.qcbagent.Agent.stamina":
		x.Stamina = value.Uint()
	case "qcb.qcbagent.Agent.skill":
		x.Skill = value.Uint()
	case "qcb.qcbagent.Agent.generation":
		x.Generation = value.Uint()
	case "qcb.qcbagent.Agent.totalTrades":
		x.TotalTrades = int32(value.Int())
	case "qcb.qcbagent.Agent.wins":
		x.Wins = int32(value.Int())
	case "qcb.qcbagent.Agent.winRateBps":
		x.WinRateBps = int32(value.Int())
	case "qcb.qcbagent.Agent.experience":
		x.Experience = int32(value.Int())
	case "qcb.qcbagent.Agent.active":
		x.Active = value.Bool()
	case "qcb.qcbagent.Agent.genesisBlock":
		x.GenesisBlock = int32(value.Int())
	case "qcb.qcbagent.Agent.parentA":
		x.ParentA = value.Interface().(string)
	case "qcb.qcbagent.Agent.parentB":
		x.ParentB = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbagent.Agent"))
		}
		panic(fmt.Errorf("message qcb.qcbagent.Agent does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agent) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "qcb.qcbagent.Agent.index":
		panic(fmt.Errorf("field index of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.nodeId":
		panic(fmt.Errorf("field nodeId of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.name":
		panic(fmt.Errorf("field name of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.agentType":
		panic(fmt.Errorf("field agentType of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.owner":
		panic(fmt.Errorf("field owner of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.dnaHash":
		panic(fmt.Errorf("field dnaHash of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.strength":
		panic(fmt.Errorf("field strength of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.agility":
		panic(fmt.Errorf("field agility of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.stamina":
		panic(fmt.Errorf("field stamina of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.skill":
		panic(fmt.Errorf("field skill of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.generation":
		panic(fmt.Errorf("field generation of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.totalTrades":
		panic(fmt.Errorf("field totalTrades of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.wins":
		panic(fmt.Errorf("field wins of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.winRateBps":
		panic(fmt.Errorf("field winRateBps of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.experience":
		panic(fmt.Errorf("field experience of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.active":
		panic(fmt.Errorf("field active of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.genesisBlock":
		panic(fmt.Errorf("field genesisBlock of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.parentA":
		panic(fmt.Errorf("field parentA of message qcb.qcbagent.Agent is not mutable"))
	case "qcb.qcbagent.Agent.parentB":
		panic(fmt.Errorf("field parentB of message qcb.qcbagent.Agent is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbagent.Agent"))
		}
		panic(fmt.Errorf("message qcb.qcbagent.Agent does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Agent) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "qcb.qcbagent.Agent.index":
		return protoreflect.ValueOfString("")
	case "qcb.qcbagent.Agent.nodeId":
		return protoreflect.ValueOfString("")
	case "qcb.qcbagent.Agent.name":
		return protoreflect.ValueOfString("")
	case "qcb.qcbagent.Agent.agentType":
		return protoreflect.ValueOfString("")
	case "qcb.qcbagent.Agent.owner":
		return protoreflect.ValueOfString("")
	case "qcb.qcbagent.Agent.dnaHash":
		return protoreflect.ValueOfString("")
	case "qcb.qcbagent.Agent.strength":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcb.qcbagent.Agent.agility":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcb.qcbagent.Agent.stamina":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcb.qcbagent.Agent.skill":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcb.qcbagent.Agent.generation":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcb.qcbagent.Agent.totalTrades":
		return protoreflect.ValueOfInt32(int32(0))
	case "qcb.qcbagent.Agent.wins":
		return protoreflect.ValueOfInt32(int32(0))
	case "qcb.qcbagent.Agent.winRateBps":
		return protoreflect.ValueOfInt32(int32(0))
	case "qcb.qcbagent.Agent.experience":
		return protoreflect.ValueOfInt32(int32(0))
	case "qcb.qcbagent.Agent.active":
		return protoreflect.ValueOfBool(false)
	case "qcb.qcbagent.Agent.genesisBlock":
		return protoreflect.ValueOfInt32(int32(0))
	case "qcb.qcbagent.Agent.parentA":
		return protoreflect.ValueOfString("")
	case "qcb.qcbagent.Agent.parentB":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbagent.Agent"))
		}
		panic(fmt.Errorf("message qcb.qcbagent.Agent does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Agent) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in qcb.qcbagent.Agent", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Agent) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Agent) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Agent) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Agent) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Agent)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.NodeId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Name)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.AgentType)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Owner)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DnaHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Strength != 0 {
			n += 1 + runtime.Sov(uint64(x.Strength))
		}
		if x.Agility != 0 {
			n += 1 + runtime.Sov(uint64(x.Agility))
		}
		if x.Stamina != 0 {
			n += 1 + runtime.Sov(uint64(x.Stamina))
		}
		if x.Skill != 0 {
			n += 1 + runtime.Sov(uint64(x.Skill))
		}
		if x.Generation != 0 {
			n += 1 + runtime.Sov(uint64(x.Generation))
		}
		if x.TotalTrades != 0 {
			n += 1 + runtime.Sov(uint64(x.TotalTrades))
		}
		if x.Wins != 0 {
			n += 1 + runtime.Sov(uint64(x.Wins))
		}
		if x.WinRateBps != 0 {
			n += 1 + runtime.Sov(uint64(x.WinRateBps))
		}
		if x.Experience != 0 {
			n += 1 + runtime.Sov(uint64(x.Experience))
		}
		if x.Active {
			n += 3
		}
		if x.GenesisBlock != 0 {
			n += 2 + runtime.Sov(uint64(x.GenesisBlock))
		}
		l = len(x.ParentA)
		if l > 0 {
			n += 2 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ParentB)
		if l > 0 {
			n += 2 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Agent)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ParentB) > 0 {
			i -= len(x.ParentB)
			copy(dAtA[i:], x.ParentB)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ParentB)))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x9a
		}
		if len(x.ParentA) > 0 {
			i -= len(x.ParentA)
			copy(dAtA[i:], x.ParentA)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ParentA)))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x92
		}
		if x.GenesisBlock != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.GenesisBlock))
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x88
		}
		if x.Active {
			i--
			if x.Active {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x80
		}
		if x.Experience != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Experience))
			i--
			dAtA[i] = 0x78
		}
		if x.WinRateBps != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.WinRateBps))
			i--
			dAtA[i] = 0x70
		}
		if x.Wins != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Wins))
			i--
			dAtA[i] = 0x68
		}
		if x.TotalTrades != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TotalTrades))
			i--
			dAtA[i] = 0x60
		}
		if x.Generation != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Generation))
			i--
			dAtA[i] = 0x58
		}
		if x.Skill != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Skill))
			i--
			dAtA[i] = 0x50
		}
		if x.Stamina != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Stamina))
			i--
			dAtA[i] = 0x48
		}
		if x.Agility != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Agility))
			i--
			dAtA[i] = 0x40
		}
		if x.Strength != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Strength))
			i--
			dAtA[i] = 0x38
		}
		if len(x.DnaHash) > 0 {
			i -= len(x.DnaHash)
			copy(dAtA[i:], x.DnaHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DnaHash)))
			i--
			dAtA[i] = 0x32
		}
		if len(x.Owner) > 0 {
			i -= len(x.Owner)
			copy(dAtA[i:], x.Owner)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Owner)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.AgentType) > 0 {
			i -= len(x.AgentType)
			copy(dAtA[i:], x.AgentType)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AgentType)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Name) > 0 {
			i -= len(x.Name)
			copy(dAtA[i:], x.Name)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Name)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.NodeId) > 0 {
			i -= len(x.NodeId)
			copy(dAtA[i:], x.NodeId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.NodeId)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Agent)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Agent: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Agent: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field NodeId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.NodeId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Name = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AgentType", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AgentType = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Owner = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DnaHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DnaHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Strength", wireType)
				}
				x.Strength = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Strength |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Agility", wireType)
				}
				x.Agility = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Agility |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Stamina", wireType)
				}
				x.Stamina = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Stamina |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 10:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Skill", wireType)
				}
				x.Skill = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Skill |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 11:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Generation", wireType)
				}
				x.Generation = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Generation |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 12:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TotalTrades", wireType)
				}
				x.TotalTrades = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TotalTrades |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 13:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Wins", wireType)
				}
				x.Wins = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Wins |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 14:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field WinRateBps", wireType)
				}
				x.WinRateBps = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.WinRateBps |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 15:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
				}
				x.Experience = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Experience |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 16:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Active = bool(v != 0)
			case 17:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GenesisBlock", wireType)
				}
				x.GenesisBlock = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.GenesisBlock |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 18:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ParentA", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ParentA = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 19:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ParentB", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ParentB = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: qcb/qcbagent/agent.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index        string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	NodeId       string `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AgentType    string `protobuf:"bytes,4,opt,name=agentType,proto3" json:"agentType,omitempty"`
	Owner        string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	DnaHash      string `protobuf:"bytes,6,opt,name=dnaHash,proto3" json:"dnaHash,omitempty"`
	Strength     uint64 `protobuf:"varint,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Agility      uint64 `protobuf:"varint,8,opt,name=agility,proto3" json:"agility,omitempty"`
	Stamina      uint64 `protobuf:"varint,9,opt,name=stamina,proto3" json:"stamina,omitempty"`
	Skill        uint64 `protobuf:"varint,10,opt,name=skill,proto3" json:"skill,omitempty"`
	Generation   uint64 `protobuf:"varint,11,opt,name=generation,proto3" json:"generation,omitempty"`
	TotalTrades  int32  `protobuf:"varint,12,opt,name=totalTrades,proto3" json:"totalTrades,omitempty"`
	Wins         int32  `protobuf:"varint,13,opt,name=wins,proto3" json:"wins,omitempty"`
	WinRateBps   int32  `protobuf:"varint,14,opt,name=winRateBps,proto3" json:"winRateBps,omitempty"`
	Experience   int32  `protobuf:"varint,15,opt,name=experience,proto3" json:"experience,omitempty"`
	Active       bool   `protobuf:"varint,16,opt,name=active,proto3" json:"active,omitempty"`
	GenesisBlock int32  `protobuf:"varint,17,opt,name=genesisBlock,proto3" json:"genesisBlock,omitempty"`
	ParentA      string `protobuf:"bytes,18,opt,name=parentA,proto3" json:"parentA,omitempty"`
	ParentB      string `protobuf:"bytes,19,opt,name=parentB,proto3" json:"parentB,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qcb_qcbagent_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_qcb_qcbagent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Agent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *Agent) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Agent) GetDnaHash() string {
	if x != nil {
		return x.DnaHash
	}
	return ""
}

func (x *Agent) GetStrength() uint64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Agent) GetAgility() uint64 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *Agent) GetStamina() uint64 {
	if x != nil {
		return x.Stamina
	}
	return 0
}

func (x *Agent) GetSkill() uint64 {
	if x != nil {
		return x.Skill
	}
	return 0
}

func (x *Agent) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Agent) GetTotalTrades() int32 {
	if x != nil {
		return x.TotalTrades
	}
	return 0
}

func (x *Agent) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *Agent) GetWinRateBps() int32 {
	if x != nil {
		return x.WinRateBps
	}
	return 0
}

func (x *Agent) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *Agent) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Agent) GetGenesisBlock() int32 {
	if x != nil {
		return x.GenesisBlock
	}
	return 0
}

func (x *Agent) GetParentA() string {
	if x != nil {
		return x.ParentA
	}
	return ""
}

func (x *Agent) GetParentB() string {
	if x != nil {
		return x.ParentB
	}
	return ""
}

var File_qcb_qcbagent_agent_proto protoreflect.FileDescriptor

var file_qcb_qcbagent_agent_proto_rawDesc = []byte{
	0x0a, 0x18, 0x71, 0x63, 0x62, 0x2f, 0x71, 0x63, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x71, 0x63, 0x62, 0x2e,
	0x71, 0x63, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x83, 0x04, 0x0a, 0x05, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x6e, 0x61, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6e, 0x61, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x74, 0x72, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x67, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x61, 0x67, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x6d,
	0x69, 0x6e, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x6d, 0x69,
	0x6e, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x69,
	0x6e, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x77, 0x69, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x42, 0x70, 0x73, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x77, 0x69, 0x6e, 0x52, 0x61, 0x74, 0x65, 0x42, 0x70, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69,
	0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x67, 0x65,
	0x6e, 0x65, 0x73, 0x69, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x41, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x41, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x18,
	0x13, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x42, 0x42, 0x85,
	0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x71, 0x63, 0x62, 0x2e, 0x71, 0x63, 0x62, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x42, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x14, 0x6f, 0x61, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x63, 0x62, 0x2f, 0x71,
	0x63, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0xa2, 0x02, 0x03, 0x51, 0x51, 0x58, 0xaa, 0x02, 0x0c,
	0x51, 0x63, 0x62, 0x2e, 0x51, 0x63, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0xca, 0x02, 0x0c, 0x51,
	0x63, 0x62, 0x5c, 0x51, 0x63, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0xe2, 0x02, 0x18, 0x51, 0x63,
	0x62, 0x5c, 0x51, 0x63, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x51, 0x63, 0x62, 0x3a, 0x3a, 0x51, 0x63,
	0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qcb_qcbagent_agent_proto_rawDescOnce sync.Once
	file_qcb_qcbagent_agent_proto_rawDescData = file_qcb_qcbagent_agent_proto_rawDesc
)

func file_qcb_qcbagent_agent_proto_rawDescGZIP() []byte {
	file_qcb_qcbagent_agent_proto_rawDescOnce.Do(func() {
		file_qcb_qcbagent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_qcb_qcbagent_agent_proto_rawDescData)
	})
	return file_qcb_qcbagent_agent_proto_rawDescData
}

var file_qcb_qcbagent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_qcb_qcbagent_agent_proto_goTypes = []interface{}{
	(*Agent)(nil), // 0: qcb.qcbagent.Agent
}
var file_qcb_qcbagent_agent_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qcb_qcbagent_agent_proto_init() }
func file_qcb_qcbagent_agent_proto_init() {
	if File_qcb_qcbagent_agent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qcb_qcbagent_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qcb_qcbagent_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qcb_qcbagent_agent_proto_goTypes,
		DependencyIndexes: file_qcb_qcbagent_agent_proto_depIdxs,
		MessageInfos:      file_qcb_qcbagent_agent_proto_msgTypes,
	}.Build()
	File_qcb_qcbagent_agent_proto = out.File
	file_qcb_qcbagent_agent_proto_rawDesc = nil
	file_qcb_qcbagent_agent_proto_goTypes = nil
	file_qcb_qcbagent_agent_proto_depIdxs = nil
}
