// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oan/oannode/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	MinValidatorStake uint64 `protobuf:"varint,1,opt,name=minValidatorStake,proto3" json:"minValidatorStake,omitempty" yaml:"min_validator_stake"`
	MinInferenceStake uint64 `protobuf:"varint,2,opt,name=minInferenceStake,proto3" json:"minInferenceStake,omitempty" yaml:"min_inference_stake"`
	MinBridgeStake    uint64 `protobuf:"varint,3,opt,name=minBridgeStake,proto3" json:"minBridgeStake,omitempty" yaml:"min_bridge_stake"`
	MinLightStake     uint64 `protobuf:"varint,4,opt,name=minLightStake,proto3" json:"minLightStake,omitempty" yaml:"min_light_stake"`
	UnbondingBlocks   uint64 `protobuf:"varint,5,opt,name=unbondingBlocks,proto3" json:"unbondingBlocks,omitempty" yaml:"unbonding_blocks"`
	MaxWalletStakePct uint64 `protobuf:"varint,6,opt,name=maxWalletStakePct,proto3" json:"maxWalletStakePct,omitempty" yaml:"max_wallet_stake_pct"`
	EpochLength       uint64 `protobuf:"varint,7,opt,name=epochLength,proto3" json:"epochLength,omitempty" yaml:"epoch_length"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e13d4f3bdcb9ce9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinValidatorStake() uint64 {
	if m != nil {
		return m.MinValidatorStake
	}
	return 0
}

func (m *Params) GetMinInferenceStake() uint64 {
	if m != nil {
		return m.MinInferenceStake
	}
	return 0
}

func (m *Params) GetMinBridgeStake() uint64 {
	if m != nil {
		return m.MinBridgeStake
	}
	return 0
}

func (m *Params) GetMinLightStake() uint64 {
	if m != nil {
		return m.MinLightStake
	}
	return 0
}

func (m *Params) GetUnbondingBlocks() uint64 {
	if m != nil {
		return m.UnbondingBlocks
	}
	return 0
}

func (m *Params) GetMaxWalletStakePct() uint64 {
	if m != nil {
		return m.MaxWalletStakePct
	}
	return 0
}

func (m *Params) GetEpochLength() uint64 {
	if m != nil {
		return m.EpochLength
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "oan.oannode.Params")
}

func init() { proto.RegisterFile("oan/oannode/params.proto", fileDescriptor_4e13d4f3bdcb9ce9) }

var fileDescriptor_4e13d4f3bdcb9ce9 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x6b, 0xdb, 0x40,
	0x18, 0xc6, 0xad, 0xd6, 0x75, 0xe1, 0x4c, 0x5b, 0x2c, 0x9b, 0x5a, 0xc8, 0x54, 0x2a, 0x9a, 0x4a,
	0xa1, 0xd6, 0xd0, 0xa9, 0x9e, 0x8a, 0x4a, 0x87, 0x82, 0x0b, 0xc6, 0x85, 0x06, 0xb2, 0x88, 0x93,
	0x74, 0x91, 0x0f, 0xeb, 0xee, 0x84, 0x74, 0x49, 0xec, 0xaf, 0x90, 0x29, 0x7b, 0x96, 0x7c, 0x84,
	0x7c, 0x8c, 0x8c, 0x1e, 0x33, 0x89, 0x60, 0x0f, 0xc9, 0xac, 0x4f, 0x10, 0x74, 0x27, 0xf9, 0x8f,
	0x92, 0x45, 0xbc, 0xe8, 0xf9, 0x3d, 0x3f, 0x5e, 0x8e, 0x17, 0x68, 0x0c, 0x52, 0x9b, 0x41, 0x4a,
	0x59, 0x80, 0xec, 0x18, 0x26, 0x90, 0xa4, 0xc3, 0x38, 0x61, 0x9c, 0xa9, 0x6d, 0x06, 0xe9, 0xb0,
	0x4c, 0xf4, 0x0e, 0x24, 0x98, 0x32, 0x5b, 0x7c, 0x65, 0xae, 0xf7, 0x42, 0x16, 0x32, 0x31, 0xda,
	0xc5, 0x24, 0xff, 0x5a, 0x57, 0x4d, 0xd0, 0x9a, 0x08, 0x8d, 0x3a, 0x06, 0x1d, 0x82, 0xe9, 0x7f,
	0x18, 0xe1, 0x00, 0x72, 0x96, 0xfc, 0xe3, 0x70, 0x8e, 0x34, 0xe5, 0xb3, 0xf2, 0xa5, 0xe9, 0x18,
	0x79, 0x66, 0xea, 0x4b, 0x48, 0xa2, 0x91, 0x45, 0x30, 0x75, 0xcf, 0x2a, 0xc6, 0x4d, 0x0b, 0xc8,
	0x9a, 0x3e, 0x2f, 0x96, 0xb6, 0x3f, 0xf4, 0x04, 0x25, 0x88, 0xfa, 0x48, 0xda, 0x5e, 0xbd, 0x64,
	0xc3, 0x15, 0xb3, 0x6f, 0x3b, 0x2c, 0xaa, 0xbf, 0xc0, 0x7b, 0x82, 0xa9, 0x93, 0xe0, 0x20, 0x2c,
	0x55, 0xaf, 0x85, 0x6a, 0x90, 0x67, 0x66, 0x7f, 0xa7, 0xf2, 0x04, 0x50, 0x79, 0x6a, 0x15, 0xf5,
	0x27, 0x78, 0x47, 0x30, 0x1d, 0xe3, 0x70, 0xc6, 0xa5, 0xa3, 0x29, 0x1c, 0x7a, 0x9e, 0x99, 0x1f,
	0x77, 0x8e, 0xa8, 0xc8, 0x2b, 0xc5, 0x61, 0x41, 0xfd, 0x0d, 0x3e, 0x9c, 0x52, 0x8f, 0xd1, 0x00,
	0xd3, 0xd0, 0x89, 0x98, 0x3f, 0x4f, 0xb5, 0x37, 0xf5, 0x3d, 0xb6, 0x80, 0xeb, 0x09, 0xc2, 0x9a,
	0xd6, 0x3b, 0xea, 0x5f, 0xd0, 0x21, 0x70, 0x71, 0x04, 0xa3, 0x08, 0x49, 0xf1, 0xc4, 0xe7, 0x5a,
	0x4b, 0x88, 0xcc, 0x3c, 0x33, 0x07, 0xe5, 0x32, 0x70, 0xe1, 0x9e, 0x0b, 0x46, 0x6e, 0xe3, 0xc6,
	0x3e, 0x2f, 0x1e, 0xa7, 0xde, 0x54, 0x7f, 0x80, 0x36, 0x8a, 0x99, 0x3f, 0x1b, 0x23, 0x1a, 0xf2,
	0x99, 0xf6, 0x56, 0x88, 0xfa, 0x79, 0x66, 0x76, 0xa5, 0x48, 0x84, 0x6e, 0x24, 0x52, 0x6b, 0xba,
	0xcf, 0x8e, 0x3e, 0x3d, 0x5e, 0x9b, 0xca, 0xc5, 0xc3, 0xcd, 0xd7, 0x5e, 0x71, 0x57, 0x8b, 0xed,
	0x65, 0xc9, 0x93, 0x70, 0xbe, 0xdd, 0xae, 0x0d, 0x65, 0xb5, 0x36, 0x94, 0xfb, 0xb5, 0xa1, 0x5c,
	0x6e, 0x8c, 0xc6, 0x6a, 0x63, 0x34, 0xee, 0x36, 0x46, 0xe3, 0xb8, 0x7b, 0xc8, 0xf3, 0x65, 0x8c,
	0x52, 0xaf, 0x25, 0x6e, 0xea, 0xfb, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x12, 0xa4, 0xfa,
	0xa5, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MinValidatorStake != that1.MinValidatorStake {
		return false
	}
	if this.MinInferenceStake != that1.MinInferenceStake {
		return false
	}
	if this.MinBridgeStake != that1.MinBridgeStake {
		return false
	}
	if this.MinLightStake != that1.MinLightStake {
		return false
	}
	if this.UnbondingBlocks != that1.UnbondingBlocks {
		return false
	}
	if this.MaxWalletStakePct != that1.MaxWalletStakePct {
		return false
	}
	if this.EpochLength != that1.EpochLength {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochLength))
		i--
		dAtA[i] = 0x38
	}
	if m.MaxWalletStakePct != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxWalletStakePct))
		i--
		dAtA[i] = 0x30
	}
	if m.UnbondingBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UnbondingBlocks))
		i--
		dAtA[i] = 0x28
	}
	if m.MinLightStake != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinLightStake))
		i--
		dAtA[i] = 0x20
	}
	if m.MinBridgeStake != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinBridgeStake))
		i--
		dAtA[i] = 0x18
	}
	if m.MinInferenceStake != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinInferenceStake))
		i--
		dAtA[i] = 0x10
	}
	if m.MinValidatorStake != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinValidatorStake))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MinValidatorStake != 0 {
		n += 1 + sovParams(uint64(m.MinValidatorStake))
	}
	if m.MinInferenceStake != 0 {
		n += 1 + sovParams(uint64(m.MinInferenceStake))
	}
	if m.MinBridgeStake != 0 {
		n += 1 + sovParams(uint64(m.MinBridgeStake))
	}
	if m.MinLightStake != 0 {
		n += 1 + sovParams(uint64(m.MinLightStake))
	}
	if m.UnbondingBlocks != 0 {
		n += 1 + sovParams(uint64(m.UnbondingBlocks))
	}
	if m.MaxWalletStakePct != 0 {
		n += 1 + sovParams(uint64(m.MaxWalletStakePct))
	}
	if m.EpochLength != 0 {
		n += 1 + sovParams(uint64(m.EpochLength))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinValidatorStake", wireType)
			}
			m.MinValidatorStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinValidatorStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinInferenceStake", wireType)
			}
			m.MinInferenceStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinInferenceStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinBridgeStake", wireType)
			}
			m.MinBridgeStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinBridgeStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLightStake", wireType)
			}
			m.MinLightStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinLightStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingBlocks", wireType)
			}
			m.UnbondingBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnbondingBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWalletStakePct", wireType)
			}
			m.MaxWalletStakePct = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxWalletStakePct |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLength", wireType)
			}
			m.EpochLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
