// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package qcbdao

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Proposal                protoreflect.MessageDescriptor
	fd_Proposal_index          protoreflect.FieldDescriptor
	fd_Proposal_title          protoreflect.FieldDescriptor
	fd_Proposal_description    protoreflect.FieldDescriptor
	fd_Proposal_proposer       protoreflect.FieldDescriptor
	fd_Proposal_votesYes       protoreflect.FieldDescriptor
	fd_Proposal_votesNo        protoreflect.FieldDescriptor
	fd_Proposal_status         protoreflect.FieldDescriptor
	fd_Proposal_startTime      protoreflect.FieldDescriptor
	fd_Proposal_endTime        protoreflect.FieldDescriptor
	fd_Proposal_executed       protoreflect.FieldDescriptor
	fd_Proposal_timelockExpiry protoreflect.FieldDescriptor
)

func init() {
	file_qcb_qcbdao_proposal_proto_init()
	md_Proposal = File_qcb_qcbdao_proposal_proto.Messages().ByName("Proposal")
	fd_Proposal_index = md_Proposal.Fields().ByName("index")
	fd_Proposal_title = md_Proposal.Fields().ByName("title")
	fd_Proposal_description = md_Proposal.Fields().ByName("description")
	fd_Proposal_proposer = md_Proposal.Fields().ByName("proposer")
	fd_Proposal_votesYes = md_Proposal.Fields().ByName("votesYes")
	fd_Proposal_votesNo = md_Proposal.Fields().ByName("votesNo")
	fd_Proposal_status = md_Proposal.Fields().ByName("status")
	fd_Proposal_startTime = md_Proposal.Fields().ByName("startTime")
	fd_Proposal_endTime = md_Proposal.Fields().ByName("endTime")
	fd_Proposal_executed = md_Proposal.Fields().ByName("executed")
	fd_Proposal_timelockExpiry = md_Proposal.Fields().ByName("timelockExpiry")
}

var _ protoreflect.Message = (*fastReflection_Proposal)(nil)

type fastReflection_Proposal Proposal

func (x *Proposal) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Proposal)(x)
}

func (x *Proposal) slowProtoReflect() protoreflect.Message {
	mi := &file_qcb_qcbdao_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Proposal_messageType fastReflection_Proposal_messageType
var _ protoreflect.MessageType = fastReflection_Proposal_messageType{}

type fastReflection_Proposal_messageType struct{}

func (x fastReflection_Proposal_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Proposal)(nil)
}
func (x fastReflection_Proposal_messageType) New() protoreflect.Message {
	return new(fastReflection_Proposal)
}
func (x fastReflection_Proposal_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Proposal
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Proposal) Descriptor() protoreflect.MessageDescriptor {
	return md_Proposal
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Proposal) Type() protoreflect.MessageType {
	return _fastReflection_Proposal_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Proposal) New() protoreflect.Message {
	return new(fastReflection_Proposal)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Proposal) Interface() protoreflect.ProtoMessage {
	return (*Proposal)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Proposal) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Index != "" {
		value := protoreflect.ValueOfString(x.Index)
		if !f(fd_Proposal_index, value) {
			return
		}
	}
	if x.Title != "" {
		value := protoreflect.ValueOfString(x.Title)
		if !f(fd_Proposal_title, value) {
			return
		}
	}
	if x.Description != "" {
		value := protoreflect.ValueOfString(x.Description)
		if !f(fd_Proposal_description, value) {
			return
		}
	}
	if x.Proposer != "" {
		value := protoreflect.ValueOfString(x.Proposer)
		if !f(fd_Proposal_proposer, value) {
			return
		}
	}
	if x.VotesYes != uint64(0) {
		value := protoreflect.ValueOfUint64(x.VotesYes)
		if !f(fd_Proposal_votesYes, value) {
			return
		}
	}
	if x.VotesNo != uint64(0) {
		value := protoreflect.ValueOfUint64(x.VotesNo)
		if !f(fd_Proposal_votesNo, value) {
			return
		}
	}
	if x.Status != "" {
		value := protoreflect.ValueOfString(x.Status)
		if !f(fd_Proposal_status, value) {
			return
		}
	}
	if x.StartTime != int32(0) {
		value := protoreflect.ValueOfInt32(x.StartTime)
		if !f(fd_Proposal_startTime, value) {
			return
		}
	}
	if x.EndTime != int32(0) {
		value := protoreflect.ValueOfInt32(x.EndTime)
		if !f(fd_Proposal_endTime, value) {
			return
		}
	}
	if x.Executed != false {
		value := protoreflect.ValueOfBool(x.Executed)
		if !f(fd_Proposal_executed, value) {
			return
		}
	}
	if x.TimelockExpiry != int32(0) {
		value := protoreflect.ValueOfInt32(x.TimelockExpiry)
		if !f(fd_Proposal_timelockExpiry, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Proposal) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "qcb.qcbdao.Proposal.index":
		return x.Index != ""
	case "qcb.qcbdao.Proposal.title":
		return x.Title != ""
	case "qcb.qcbdao.Proposal.description":
		return x.Description != ""
	case "qcb.qcbdao.Proposal.proposer":
		return x.Proposer != ""
	case "qcb.qcbdao.Proposal.votesYes":
		return x.VotesYes != uint64(0)
	case "qcb.qcbdao.Proposal.votesNo":
		return x.VotesNo != uint64(0)
	case "qcb.qcbdao.Proposal.status":
		return x.Status != ""
	case "qcb.qcbdao.Proposal.startTime":
		return x.StartTime != int32(0)
	case "qcb.qcbdao.Proposal.endTime":
		return x.EndTime != int32(0)
	case "qcb.qcbdao.Proposal.executed":
		return x.Executed != false
	case "qcb.qcbdao.Proposal.timelockExpiry":
		return x.TimelockExpiry != int32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbdao.Proposal"))
		}
		panic(fmt.Errorf("message qcb.qcbdao.Proposal does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Proposal) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "qcb.qcbdao.Proposal.index":
		x.Index = ""
	case "qcb.qcbdao.Proposal.title":
		x.Title = ""
	case "qcb.qcbdao.Proposal.description":
		x.Description = ""
	case "qcb.qcbdao.Proposal.proposer":
		x.Proposer = ""
	case "qcb.qcbdao.Proposal.votesYes":
		x.VotesYes = uint64(0)
	case "qcb.qcbdao.Proposal.votesNo":
		x.VotesNo = uint64(0)
	case "qcb.qcbdao.Proposal.status":
		x.Status = ""
	case "qcb.qcbdao.Proposal.startTime":
		x.StartTime = int32(0)
	case "qcb.qcbdao.Proposal.endTime":
		x.EndTime = int32(0)
	case "qcb.qcbdao.Proposal.executed":
		x.Executed = false
	case "qcb.qcbdao.Proposal.timelockExpiry":
		x.TimelockExpiry = int32(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbdao.Proposal"))
		}
		panic(fmt.Errorf("message qcb.qcbdao.Proposal does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Proposal) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "qcb.qcbdao.Proposal.index":
		value := x.Index
		return protoreflect.ValueOfString(value)
	case "qcb.qcbdao.Proposal.title":
		value := x.Title
		return protoreflect.ValueOfString(value)
	case "qcb.qcbdao.Proposal.description":
		value := x.Description
		return protoreflect.ValueOfString(value)
	case "qcb.qcbdao.Proposal.proposer":
		value := x.Proposer
		return protoreflect.ValueOfString(value)
	case "qcb.qcbdao.Proposal.votesYes":
		value := x.VotesYes
		return protoreflect.ValueOfUint64(value)
	case "qcb.qcbdao.Proposal.votesNo":
		value := x.VotesNo
		return protoreflect.ValueOfUint64(value)
	case "qcb.qcbdao.Proposal.status":
		value := x.Status
		return protoreflect.ValueOfString(value)
	case "qcb.qcbdao.Proposal.startTime":
		value := x.StartTime
		return protoreflect.ValueOfInt32(value)
	case "qcb.qcbdao.Proposal.endTime":
		value := x.EndTime
		return protoreflect.ValueOfInt32(value)
	case "qcb.qcbdao.Proposal.executed":
		value := x.Executed
		return protoreflect.ValueOfBool(value)
	case "qcb.qcbdao.Proposal.timelockExpiry":
		value := x.TimelockExpiry
		return protoreflect.ValueOfInt32(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbdao.Proposal"))
		}
		panic(fmt.Errorf("message qcb.qcbdao.Proposal does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Proposal) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "qcb.qcbdao.Proposal.index":
		x.Index = value.Interface().(string)
	case "qcb.qcbdao.Proposal.title":
		x.Title = value.Interface().(string)
	case "qcb.qcbdao.Proposal.description":
		x.Description = value.Interface().(string)
	case "qcb.qcbdao.Proposal.proposer":
		x.Proposer = value.Interface().(string)
	case "qcb.qcbdao.Proposal.votesYes":
		x.VotesYes = value.Uint()
	case "qcb.qcbdao.Proposal.votesNo":
		x.VotesNo = value.Uint()
	case "qcb.qcbdao.Proposal.status":
		x.Status = value.Interface().(string)
	case "qcb.qcbdao.Proposal.startTime":
		x.StartTime = int32(value.Int())
	case "qcb.qcbdao.Proposal.endTime":
		x.EndTime = int32(value.Int())
	case "qcb.qcbdao.Proposal.executed":
		x.Executed = value.Bool()
	case "qcb.qcbdao.Proposal.timelockExpiry":
		x.TimelockExpiry = int32(value.Int())
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbdao.Proposal"))
		}
		panic(fmt.Errorf("message qcb.qcbdao.Proposal does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Proposal) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "qcb.qcbdao.Proposal.index":
		panic(fmt.Errorf("field index of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.title":
		panic(fmt.Errorf("field title of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.description":
		panic(fmt.Errorf("field description of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.proposer":
		panic(fmt.Errorf("field proposer of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.votesYes":
		panic(fmt.Errorf("field votesYes of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.votesNo":
		panic(fmt.Errorf("field votesNo of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.status":
		panic(fmt.Errorf("field status of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.startTime":
		panic(fmt.Errorf("field startTime of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.endTime":
		panic(fmt.Errorf("field endTime of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.executed":
		panic(fmt.Errorf("field executed of message qcb.qcbdao.Proposal is not mutable"))
	case "qcb.qcbdao.Proposal.timelockExpiry":
		panic(fmt.Errorf("field timelockExpiry of message qcb.qcbdao.Proposal is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbdao.Proposal"))
		}
		panic(fmt.Errorf("message qcb.qcbdao.Proposal does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Proposal) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "qcb.qcbdao.Proposal.index":
		return protoreflect.ValueOfString("")
	case "qcb.qcbdao.Proposal.title":
		return protoreflect.ValueOfString("")
	case "qcb.qcbdao.Proposal.description":
		return protoreflect.ValueOfString("")
	case "qcb.qcbdao.Proposal.proposer":
		return protoreflect.ValueOfString("")
	case "qcb.qcbdao.Proposal.votesYes":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcb.qcbdao.Proposal.votesNo":
		return protoreflect.ValueOfUint64(uint64(0))
	case "qcb.qcbdao.Proposal.status":
		return protoreflect.ValueOfString("")
	case "qcb.qcbdao.Proposal.startTime":
		return protoreflect.ValueOfInt32(int32(0))
	case "qcb.qcbdao.Proposal.endTime":
		return protoreflect.ValueOfInt32(int32(0))
	case "qcb.qcbdao.Proposal.executed":
		return protoreflect.ValueOfBool(false)
	case "qcb.qcbdao.Proposal.timelockExpiry":
		return protoreflect.ValueOfInt32(int32(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: qcb.qcbdao.Proposal"))
		}
		panic(fmt.Errorf("message qcb.qcbdao.Proposal does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Proposal) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in qcb.qcbdao.Proposal", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Proposal) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Proposal) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Proposal) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Proposal) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Proposal)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Index)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Title)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Description)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Proposer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.VotesYes != 0 {
			n += 1 + runtime.Sov(uint64(x.VotesYes))
		}
		if x.VotesNo != 0 {
			n += 1 + runtime.Sov(uint64(x.VotesNo))
		}
		l = len(x.Status)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.StartTime != 0 {
			n += 1 + runtime.Sov(uint64(x.StartTime))
		}
		if x.EndTime != 0 {
			n += 1 + runtime.Sov(uint64(x.EndTime))
		}
		if x.Executed {
			n += 2
		}
		if x.TimelockExpiry != 0 {
			n += 1 + runtime.Sov(uint64(x.TimelockExpiry))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Proposal)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.TimelockExpiry != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TimelockExpiry))
			i--
			dAtA[i] = 0x58
		}
		if x.Executed {
			i--
			if x.Executed {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x50
		}
		if x.EndTime != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.EndTime))
			i--
			dAtA[i] = 0x48
		}
		if x.StartTime != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.StartTime))
			i--
			dAtA[i] = 0x40
		}
		if len(x.Status) > 0 {
			i -= len(x.Status)
			copy(dAtA[i:], x.Status)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Status)))
			i--
			dAtA[i] = 0x3a
		}
		if x.VotesNo != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.VotesNo))
			i--
			dAtA[i] = 0x30
		}
		if x.VotesYes != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.VotesYes))
			i--
			dAtA[i] = 0x28
		}
		if len(x.Proposer) > 0 {
			i -= len(x.Proposer)
			copy(dAtA[i:], x.Proposer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Proposer)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Description) > 0 {
			i -= len(x.Description)
			copy(dAtA[i:], x.Description)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Description)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Title) > 0 {
			i -= len(x.Title)
			copy(dAtA[i:], x.Title)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Title)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Index) > 0 {
			i -= len(x.Index)
			copy(dAtA[i:], x.Index)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Index)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Proposal)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Proposal: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Proposal: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Index = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Title = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Description = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Proposer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Proposer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VotesYes", wireType)
				}
				x.VotesYes = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.VotesYes |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field VotesNo", wireType)
				}
				x.VotesNo = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.VotesNo |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Status = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
				}
				x.StartTime = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.StartTime |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 9:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
				}
				x.EndTime = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.EndTime |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 10:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Executed", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Executed = bool(v != 0)
			case 11:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TimelockExpiry", wireType)
				}
				x.TimelockExpiry = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TimelockExpiry |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: qcb/qcbdao/proposal.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index          string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Title          string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Proposer       string `protobuf:"bytes,4,opt,name=proposer,proto3" json:"proposer,omitempty"`
	VotesYes       uint64 `protobuf:"varint,5,opt,name=votesYes,proto3" json:"votesYes,omitempty"`
	VotesNo        uint64 `protobuf:"varint,6,opt,name=votesNo,proto3" json:"votesNo,omitempty"`
	Status         string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	StartTime      int32  `protobuf:"varint,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime        int32  `protobuf:"varint,9,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Executed       bool   `protobuf:"varint,10,opt,name=executed,proto3" json:"executed,omitempty"`
	TimelockExpiry int32  `protobuf:"varint,11,opt,name=timelockExpiry,proto3" json:"timelockExpiry,omitempty"`
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qcb_qcbdao_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_qcb_qcbdao_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Proposal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Proposal) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Proposal) GetProposer() string {
	if x != nil {
		return x.Proposer
	}
	return ""
}

func (x *Proposal) GetVotesYes() uint64 {
	if x != nil {
		return x.VotesYes
	}
	return 0
}

func (x *Proposal) GetVotesNo() uint64 {
	if x != nil {
		return x.VotesNo
	}
	return 0
}

func (x *Proposal) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Proposal) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Proposal) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Proposal) GetExecuted() bool {
	if x != nil {
		return x.Executed
	}
	return false
}

func (x *Proposal) GetTimelockExpiry() int32 {
	if x != nil {
		return x.TimelockExpiry
	}
	return 0
}

var File_qcb_qcbdao_proposal_proto protoreflect.FileDescriptor

var file_qcb_qcbdao_proposal_proto_rawDesc = []byte{
	0x0a, 0x19, 0x71, 0x63, 0x62, 0x2f, 0x71, 0x63, 0x62, 0x64, 0x61, 0x6f, 0x2f, 0x70, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x71, 0x63, 0x62,
	0x2e, 0x71, 0x63, 0x62, 0x64, 0x61, 0x6f, 0x22, 0xbe, 0x02, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x59, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x76, 0x6f, 0x74, 0x65, 0x73, 0x59, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x6f,
	0x74, 0x65, 0x73, 0x4e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x6f, 0x74,
	0x65, 0x73, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x64,
	0x12, 0x26, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x6f, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x6f,
	0x63, 0x6b, 0x45, 0x78, 0x70, 0x69, 0x72, 0x79, 0x42, 0x7c, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x2e,
	0x71, 0x63, 0x62, 0x2e, 0x71, 0x63, 0x62, 0x64, 0x61, 0x6f, 0x42, 0x0d, 0x50, 0x72, 0x6f, 0x70,
	0x6f, 0x73, 0x61, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x12, 0x6f, 0x61, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x71, 0x63, 0x62, 0x2f, 0x71, 0x63, 0x62, 0x64, 0x61, 0x6f, 0xa2,
	0x02, 0x03, 0x51, 0x51, 0x58, 0xaa, 0x02, 0x0a, 0x51, 0x63, 0x62, 0x2e, 0x51, 0x63, 0x62, 0x64,
	0x61, 0x6f, 0xca, 0x02, 0x0a, 0x51, 0x63, 0x62, 0x5c, 0x51, 0x63, 0x62, 0x64, 0x61, 0x6f, 0xe2,
	0x02, 0x16, 0x51, 0x63, 0x62, 0x5c, 0x51, 0x63, 0x62, 0x64, 0x61, 0x6f, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x51, 0x63, 0x62, 0x3a, 0x3a,
	0x51, 0x63, 0x62, 0x64, 0x61, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_qcb_qcbdao_proposal_proto_rawDescOnce sync.Once
	file_qcb_qcbdao_proposal_proto_rawDescData = file_qcb_qcbdao_proposal_proto_rawDesc
)

func file_qcb_qcbdao_proposal_proto_rawDescGZIP() []byte {
	file_qcb_qcbdao_proposal_proto_rawDescOnce.Do(func() {
		file_qcb_qcbdao_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_qcb_qcbdao_proposal_proto_rawDescData)
	})
	return file_qcb_qcbdao_proposal_proto_rawDescData
}

var file_qcb_qcbdao_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_qcb_qcbdao_proposal_proto_goTypes = []interface{}{
	(*Proposal)(nil), // 0: qcb.qcbdao.Proposal
}
var file_qcb_qcbdao_proposal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qcb_qcbdao_proposal_proto_init() }
func file_qcb_qcbdao_proposal_proto_init() {
	if File_qcb_qcbdao_proposal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qcb_qcbdao_proposal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qcb_qcbdao_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qcb_qcbdao_proposal_proto_goTypes,
		DependencyIndexes: file_qcb_qcbdao_proposal_proto_depIdxs,
		MessageInfos:      file_qcb_qcbdao_proposal_proto_msgTypes,
	}.Build()
	File_qcb_qcbdao_proposal_proto = out.File
	file_qcb_qcbdao_proposal_proto_rawDesc = nil
	file_qcb_qcbdao_proposal_proto_goTypes = nil
	file_qcb_qcbdao_proposal_proto_depIdxs = nil
}
