// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: qcb/antirug/tx.proto

package antirug

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName     = "/qcb.antirug.Msg/UpdateParams"
	Msg_RegisterToken_FullMethodName    = "/qcb.antirug.Msg/RegisterToken"
	Msg_LockLiquidity_FullMethodName    = "/qcb.antirug.Msg/LockLiquidity"
	Msg_DeclareMintLimit_FullMethodName = "/qcb.antirug.Msg/DeclareMintLimit"
	Msg_FlagToken_FullMethodName        = "/qcb.antirug.Msg/FlagToken"
	Msg_FreezeToken_FullMethodName      = "/qcb.antirug.Msg/FreezeToken"
	Msg_UnfreezeToken_FullMethodName    = "/qcb.antirug.Msg/UnfreezeToken"
	Msg_RequestUpgrade_FullMethodName   = "/qcb.antirug.Msg/RequestUpgrade"
	Msg_ApproveToken_FullMethodName     = "/qcb.antirug.Msg/ApproveToken"
	Msg_SetModuleActive_FullMethodName  = "/qcb.antirug.Msg/SetModuleActive"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	RegisterToken(ctx context.Context, in *MsgRegisterToken, opts ...grpc.CallOption) (*MsgRegisterTokenResponse, error)
	LockLiquidity(ctx context.Context, in *MsgLockLiquidity, opts ...grpc.CallOption) (*MsgLockLiquidityResponse, error)
	DeclareMintLimit(ctx context.Context, in *MsgDeclareMintLimit, opts ...grpc.CallOption) (*MsgDeclareMintLimitResponse, error)
	FlagToken(ctx context.Context, in *MsgFlagToken, opts ...grpc.CallOption) (*MsgFlagTokenResponse, error)
	FreezeToken(ctx context.Context, in *MsgFreezeToken, opts ...grpc.CallOption) (*MsgFreezeTokenResponse, error)
	UnfreezeToken(ctx context.Context, in *MsgUnfreezeToken, opts ...grpc.CallOption) (*MsgUnfreezeTokenResponse, error)
	RequestUpgrade(ctx context.Context, in *MsgRequestUpgrade, opts ...grpc.CallOption) (*MsgRequestUpgradeResponse, error)
	ApproveToken(ctx context.Context, in *MsgApproveToken, opts ...grpc.CallOption) (*MsgApproveTokenResponse, error)
	SetModuleActive(ctx context.Context, in *MsgSetModuleActive, opts ...grpc.CallOption) (*MsgSetModuleActiveResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterToken(ctx context.Context, in *MsgRegisterToken, opts ...grpc.CallOption) (*MsgRegisterTokenResponse, error) {
	out := new(MsgRegisterTokenResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LockLiquidity(ctx context.Context, in *MsgLockLiquidity, opts ...grpc.CallOption) (*MsgLockLiquidityResponse, error) {
	out := new(MsgLockLiquidityResponse)
	err := c.cc.Invoke(ctx, Msg_LockLiquidity_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeclareMintLimit(ctx context.Context, in *MsgDeclareMintLimit, opts ...grpc.CallOption) (*MsgDeclareMintLimitResponse, error) {
	out := new(MsgDeclareMintLimitResponse)
	err := c.cc.Invoke(ctx, Msg_DeclareMintLimit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FlagToken(ctx context.Context, in *MsgFlagToken, opts ...grpc.CallOption) (*MsgFlagTokenResponse, error) {
	out := new(MsgFlagTokenResponse)
	err := c.cc.Invoke(ctx, Msg_FlagToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) FreezeToken(ctx context.Context, in *MsgFreezeToken, opts ...grpc.CallOption) (*MsgFreezeTokenResponse, error) {
	out := new(MsgFreezeTokenResponse)
	err := c.cc.Invoke(ctx, Msg_FreezeToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnfreezeToken(ctx context.Context, in *MsgUnfreezeToken, opts ...grpc.CallOption) (*MsgUnfreezeTokenResponse, error) {
	out := new(MsgUnfreezeTokenResponse)
	err := c.cc.Invoke(ctx, Msg_UnfreezeToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RequestUpgrade(ctx context.Context, in *MsgRequestUpgrade, opts ...grpc.CallOption) (*MsgRequestUpgradeResponse, error) {
	out := new(MsgRequestUpgradeResponse)
	err := c.cc.Invoke(ctx, Msg_RequestUpgrade_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ApproveToken(ctx context.Context, in *MsgApproveToken, opts ...grpc.CallOption) (*MsgApproveTokenResponse, error) {
	out := new(MsgApproveTokenResponse)
	err := c.cc.Invoke(ctx, Msg_ApproveToken_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetModuleActive(ctx context.Context, in *MsgSetModuleActive, opts ...grpc.CallOption) (*MsgSetModuleActiveResponse, error) {
	out := new(MsgSetModuleActiveResponse)
	err := c.cc.Invoke(ctx, Msg_SetModuleActive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	RegisterToken(context.Context, *MsgRegisterToken) (*MsgRegisterTokenResponse, error)
	LockLiquidity(context.Context, *MsgLockLiquidity) (*MsgLockLiquidityResponse, error)
	DeclareMintLimit(context.Context, *MsgDeclareMintLimit) (*MsgDeclareMintLimitResponse, error)
	FlagToken(context.Context, *MsgFlagToken) (*MsgFlagTokenResponse, error)
	FreezeToken(context.Context, *MsgFreezeToken) (*MsgFreezeTokenResponse, error)
	UnfreezeToken(context.Context, *MsgUnfreezeToken) (*MsgUnfreezeTokenResponse, error)
	RequestUpgrade(context.Context, *MsgRequestUpgrade) (*MsgRequestUpgradeResponse, error)
	ApproveToken(context.Context, *MsgApproveToken) (*MsgApproveTokenResponse, error)
	SetModuleActive(context.Context, *MsgSetModuleActive) (*MsgSetModuleActiveResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) RegisterToken(context.Context, *MsgRegisterToken) (*MsgRegisterTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterToken not implemented")
}
func (UnimplementedMsgServer) LockLiquidity(context.Context, *MsgLockLiquidity) (*MsgLockLiquidityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockLiquidity not implemented")
}
func (UnimplementedMsgServer) DeclareMintLimit(context.Context, *MsgDeclareMintLimit) (*MsgDeclareMintLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeclareMintLimit not implemented")
}
func (UnimplementedMsgServer) FlagToken(context.Context, *MsgFlagToken) (*MsgFlagTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlagToken not implemented")
}
func (UnimplementedMsgServer) FreezeToken(context.Context, *MsgFreezeToken) (*MsgFreezeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezeToken not implemented")
}
func (UnimplementedMsgServer) UnfreezeToken(context.Context, *MsgUnfreezeToken) (*MsgUnfreezeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfreezeToken not implemented")
}
func (UnimplementedMsgServer) RequestUpgrade(context.Context, *MsgRequestUpgrade) (*MsgRequestUpgradeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUpgrade not implemented")
}
func (UnimplementedMsgServer) ApproveToken(context.Context, *MsgApproveToken) (*MsgApproveTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveToken not implemented")
}
func (UnimplementedMsgServer) SetModuleActive(context.Context, *MsgSetModuleActive) (*MsgSetModuleActiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetModuleActive not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterToken(ctx, req.(*MsgRegisterToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LockLiquidity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLockLiquidity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LockLiquidity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_LockLiquidity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LockLiquidity(ctx, req.(*MsgLockLiquidity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeclareMintLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeclareMintLimit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeclareMintLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeclareMintLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeclareMintLimit(ctx, req.(*MsgDeclareMintLimit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FlagToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFlagToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FlagToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FlagToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FlagToken(ctx, req.(*MsgFlagToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_FreezeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFreezeToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FreezeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_FreezeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FreezeToken(ctx, req.(*MsgFreezeToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnfreezeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnfreezeToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnfreezeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UnfreezeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnfreezeToken(ctx, req.(*MsgUnfreezeToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RequestUpgrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestUpgrade)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestUpgrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RequestUpgrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestUpgrade(ctx, req.(*MsgRequestUpgrade))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ApproveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgApproveToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ApproveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ApproveToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ApproveToken(ctx, req.(*MsgApproveToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetModuleActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetModuleActive)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetModuleActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SetModuleActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetModuleActive(ctx, req.(*MsgSetModuleActive))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qcb.antirug.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterToken",
			Handler:    _Msg_RegisterToken_Handler,
		},
		{
			MethodName: "LockLiquidity",
			Handler:    _Msg_LockLiquidity_Handler,
		},
		{
			MethodName: "DeclareMintLimit",
			Handler:    _Msg_DeclareMintLimit_Handler,
		},
		{
			MethodName: "FlagToken",
			Handler:    _Msg_FlagToken_Handler,
		},
		{
			MethodName: "FreezeToken",
			Handler:    _Msg_FreezeToken_Handler,
		},
		{
			MethodName: "UnfreezeToken",
			Handler:    _Msg_UnfreezeToken_Handler,
		},
		{
			MethodName: "RequestUpgrade",
			Handler:    _Msg_RequestUpgrade_Handler,
		},
		{
			MethodName: "ApproveToken",
			Handler:    _Msg_ApproveToken_Handler,
		},
		{
			MethodName: "SetModuleActive",
			Handler:    _Msg_SetModuleActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qcb/antirug/tx.proto",
}
