// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qcb/qcbmarket/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgListAgentForHire struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AgentId      string `protobuf:"bytes,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	PricePerTask uint64 `protobuf:"varint,3,opt,name=pricePerTask,proto3" json:"pricePerTask,omitempty"`
	Skills       string `protobuf:"bytes,4,opt,name=skills,proto3" json:"skills,omitempty"`
}

func (m *MsgListAgentForHire) Reset()         { *m = MsgListAgentForHire{} }
func (m *MsgListAgentForHire) String() string { return proto.CompactTextString(m) }
func (*MsgListAgentForHire) ProtoMessage()    {}
func (*MsgListAgentForHire) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{2}
}
func (m *MsgListAgentForHire) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgListAgentForHire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgListAgentForHire.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgListAgentForHire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgListAgentForHire.Merge(m, src)
}
func (m *MsgListAgentForHire) XXX_Size() int {
	return m.Size()
}
func (m *MsgListAgentForHire) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgListAgentForHire.DiscardUnknown(m)
}

var xxx_messageInfo_MsgListAgentForHire proto.InternalMessageInfo

func (m *MsgListAgentForHire) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgListAgentForHire) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *MsgListAgentForHire) GetPricePerTask() uint64 {
	if m != nil {
		return m.PricePerTask
	}
	return 0
}

func (m *MsgListAgentForHire) GetSkills() string {
	if m != nil {
		return m.Skills
	}
	return ""
}

type MsgListAgentForHireResponse struct {
	ListingId    string `protobuf:"bytes,1,opt,name=listingId,proto3" json:"listingId,omitempty"`
	PricePerTask uint64 `protobuf:"varint,2,opt,name=pricePerTask,proto3" json:"pricePerTask,omitempty"`
}

func (m *MsgListAgentForHireResponse) Reset()         { *m = MsgListAgentForHireResponse{} }
func (m *MsgListAgentForHireResponse) String() string { return proto.CompactTextString(m) }
func (*MsgListAgentForHireResponse) ProtoMessage()    {}
func (*MsgListAgentForHireResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{3}
}
func (m *MsgListAgentForHireResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgListAgentForHireResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgListAgentForHireResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgListAgentForHireResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgListAgentForHireResponse.Merge(m, src)
}
func (m *MsgListAgentForHireResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgListAgentForHireResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgListAgentForHireResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgListAgentForHireResponse proto.InternalMessageInfo

func (m *MsgListAgentForHireResponse) GetListingId() string {
	if m != nil {
		return m.ListingId
	}
	return ""
}

func (m *MsgListAgentForHireResponse) GetPricePerTask() uint64 {
	if m != nil {
		return m.PricePerTask
	}
	return 0
}

type MsgHireAgent struct {
	Creator         string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ListingId       string `protobuf:"bytes,2,opt,name=listingId,proto3" json:"listingId,omitempty"`
	TaskDescription string `protobuf:"bytes,3,opt,name=taskDescription,proto3" json:"taskDescription,omitempty"`
	Budget          uint64 `protobuf:"varint,4,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (m *MsgHireAgent) Reset()         { *m = MsgHireAgent{} }
func (m *MsgHireAgent) String() string { return proto.CompactTextString(m) }
func (*MsgHireAgent) ProtoMessage()    {}
func (*MsgHireAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{4}
}
func (m *MsgHireAgent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgHireAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgHireAgent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgHireAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHireAgent.Merge(m, src)
}
func (m *MsgHireAgent) XXX_Size() int {
	return m.Size()
}
func (m *MsgHireAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHireAgent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHireAgent proto.InternalMessageInfo

func (m *MsgHireAgent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgHireAgent) GetListingId() string {
	if m != nil {
		return m.ListingId
	}
	return ""
}

func (m *MsgHireAgent) GetTaskDescription() string {
	if m != nil {
		return m.TaskDescription
	}
	return ""
}

func (m *MsgHireAgent) GetBudget() uint64 {
	if m != nil {
		return m.Budget
	}
	return 0
}

type MsgHireAgentResponse struct {
	ContractId string `protobuf:"bytes,1,opt,name=contractId,proto3" json:"contractId,omitempty"`
	AgentId    string `protobuf:"bytes,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Budget     uint64 `protobuf:"varint,3,opt,name=budget,proto3" json:"budget,omitempty"`
}

func (m *MsgHireAgentResponse) Reset()         { *m = MsgHireAgentResponse{} }
func (m *MsgHireAgentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgHireAgentResponse) ProtoMessage()    {}
func (*MsgHireAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{5}
}
func (m *MsgHireAgentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgHireAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgHireAgentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgHireAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgHireAgentResponse.Merge(m, src)
}
func (m *MsgHireAgentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgHireAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgHireAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgHireAgentResponse proto.InternalMessageInfo

func (m *MsgHireAgentResponse) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *MsgHireAgentResponse) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *MsgHireAgentResponse) GetBudget() uint64 {
	if m != nil {
		return m.Budget
	}
	return 0
}

type MsgRateAgent struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AgentId    string `protobuf:"bytes,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	ContractId string `protobuf:"bytes,3,opt,name=contractId,proto3" json:"contractId,omitempty"`
	Rating     uint64 `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Review     string `protobuf:"bytes,5,opt,name=review,proto3" json:"review,omitempty"`
}

func (m *MsgRateAgent) Reset()         { *m = MsgRateAgent{} }
func (m *MsgRateAgent) String() string { return proto.CompactTextString(m) }
func (*MsgRateAgent) ProtoMessage()    {}
func (*MsgRateAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{6}
}
func (m *MsgRateAgent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRateAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRateAgent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRateAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRateAgent.Merge(m, src)
}
func (m *MsgRateAgent) XXX_Size() int {
	return m.Size()
}
func (m *MsgRateAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRateAgent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRateAgent proto.InternalMessageInfo

func (m *MsgRateAgent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRateAgent) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *MsgRateAgent) GetContractId() string {
	if m != nil {
		return m.ContractId
	}
	return ""
}

func (m *MsgRateAgent) GetRating() uint64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *MsgRateAgent) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

type MsgRateAgentResponse struct {
	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewRating uint64 `protobuf:"varint,2,opt,name=newRating,proto3" json:"newRating,omitempty"`
}

func (m *MsgRateAgentResponse) Reset()         { *m = MsgRateAgentResponse{} }
func (m *MsgRateAgentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRateAgentResponse) ProtoMessage()    {}
func (*MsgRateAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9f181f863106f19a, []int{7}
}
func (m *MsgRateAgentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRateAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRateAgentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRateAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRateAgentResponse.Merge(m, src)
}
func (m *MsgRateAgentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRateAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRateAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRateAgentResponse proto.InternalMessageInfo

func (m *MsgRateAgentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MsgRateAgentResponse) GetNewRating() uint64 {
	if m != nil {
		return m.NewRating
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "qcb.qcbmarket.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "qcb.qcbmarket.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgListAgentForHire)(nil), "qcb.qcbmarket.MsgListAgentForHire")
	proto.RegisterType((*MsgListAgentForHireResponse)(nil), "qcb.qcbmarket.MsgListAgentForHireResponse")
	proto.RegisterType((*MsgHireAgent)(nil), "qcb.qcbmarket.MsgHireAgent")
	proto.RegisterType((*MsgHireAgentResponse)(nil), "qcb.qcbmarket.MsgHireAgentResponse")
	proto.RegisterType((*MsgRateAgent)(nil), "qcb.qcbmarket.MsgRateAgent")
	proto.RegisterType((*MsgRateAgentResponse)(nil), "qcb.qcbmarket.MsgRateAgentResponse")
}

func init() { proto.RegisterFile("qcb/qcbmarket/tx.proto", fileDescriptor_9f181f863106f19a) }

var fileDescriptor_9f181f863106f19a = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6b, 0xd4, 0x4e,
	0x18, 0xde, 0xec, 0xb6, 0xdb, 0x5f, 0xe6, 0xb7, 0x52, 0x8d, 0xfd, 0x48, 0x53, 0x49, 0x4b, 0x04,
	0x59, 0x16, 0xdc, 0x60, 0x05, 0x91, 0xde, 0x5a, 0x44, 0x2c, 0xb8, 0x52, 0xe2, 0xc7, 0xc1, 0x4b,
	0x99, 0x24, 0x43, 0x3a, 0x6c, 0x37, 0x93, 0xce, 0x4c, 0xbf, 0x6e, 0xe2, 0xd1, 0x93, 0x20, 0x78,
	0xf6, 0xe8, 0xb1, 0x07, 0xc1, 0x7f, 0xa1, 0xc7, 0xe2, 0xc9, 0x93, 0x48, 0x17, 0xdc, 0x7f, 0x43,
	0x32, 0x93, 0x8f, 0x4d, 0xb2, 0x6e, 0x2f, 0xbb, 0x79, 0x9f, 0xf7, 0x9d, 0xf7, 0x79, 0x9e, 0x77,
	0x3e, 0xc0, 0xd2, 0xa1, 0xe7, 0xda, 0x87, 0x9e, 0x3b, 0x80, 0xb4, 0x8f, 0xb8, 0xcd, 0x4f, 0xbb,
	0x11, 0x25, 0x9c, 0x68, 0x37, 0x0e, 0x3d, 0xb7, 0x9b, 0xe1, 0xc6, 0x2d, 0x38, 0xc0, 0x21, 0xb1,
	0xc5, 0xaf, 0xac, 0x30, 0x96, 0x3d, 0xc2, 0x06, 0x84, 0xd9, 0x03, 0x16, 0xd8, 0xc7, 0x0f, 0xe2,
	0xbf, 0x24, 0xb1, 0x22, 0x13, 0x7b, 0x22, 0xb2, 0x65, 0x90, 0xa4, 0x16, 0x02, 0x12, 0x10, 0x89,
	0xc7, 0x5f, 0x09, 0x6a, 0x14, 0x35, 0x44, 0x90, 0xc2, 0x41, 0xb2, 0xc2, 0xfa, 0xae, 0x80, 0xf9,
	0x1e, 0x0b, 0x5e, 0x47, 0x3e, 0xe4, 0x68, 0x57, 0x64, 0xb4, 0x47, 0x40, 0x85, 0x47, 0x7c, 0x9f,
	0x50, 0xcc, 0xcf, 0x74, 0x65, 0x5d, 0x69, 0xab, 0xdb, 0xfa, 0x8f, 0x6f, 0xf7, 0x17, 0x12, 0xaa,
	0x2d, 0xdf, 0xa7, 0x88, 0xb1, 0x97, 0x9c, 0xe2, 0x30, 0x70, 0xf2, 0x52, 0xed, 0x31, 0x68, 0xca,
	0xde, 0x7a, 0x7d, 0x5d, 0x69, 0xff, 0xbf, 0xb1, 0xd8, 0x2d, 0x98, 0xec, 0xca, 0xf6, 0xdb, 0xea,
	0xc5, 0xaf, 0xb5, 0xda, 0xd7, 0xd1, 0x79, 0x47, 0x71, 0x92, 0xfa, 0xcd, 0x8d, 0xf7, 0xa3, 0xf3,
	0x4e, 0xde, 0xe9, 0xc3, 0xe8, 0xbc, 0xb3, 0x16, 0x8b, 0x3e, 0x1d, 0x93, 0x5d, 0x52, 0x69, 0xad,
	0x80, 0xe5, 0x12, 0xe4, 0x20, 0x16, 0x91, 0x90, 0x21, 0xeb, 0x93, 0x02, 0x6e, 0xf7, 0x58, 0xf0,
	0x1c, 0x33, 0xbe, 0x15, 0xa0, 0x90, 0x3f, 0x25, 0xf4, 0x19, 0xa6, 0x48, 0xd3, 0xc1, 0x9c, 0x47,
	0x11, 0xe4, 0x84, 0x4a, 0x5b, 0x4e, 0x1a, 0xc6, 0x19, 0x18, 0x57, 0xee, 0xf8, 0x42, 0xbb, 0xea,
	0xa4, 0xa1, 0x66, 0x81, 0x56, 0x44, 0xb1, 0x87, 0x76, 0x11, 0x7d, 0x05, 0x59, 0x5f, 0x6f, 0xac,
	0x2b, 0xed, 0x19, 0xa7, 0x80, 0x69, 0x4b, 0xa0, 0xc9, 0xfa, 0xf8, 0xe0, 0x80, 0xe9, 0x33, 0x62,
	0x71, 0x12, 0x6d, 0xb6, 0x62, 0x5b, 0x29, 0x87, 0xb5, 0x07, 0x56, 0x27, 0x88, 0x4a, 0x45, 0x6b,
	0x77, 0x80, 0x7a, 0x80, 0x19, 0xc7, 0x61, 0xb0, 0xe3, 0x27, 0xf2, 0x72, 0xa0, 0x22, 0xa3, 0x5e,
	0x95, 0x61, 0x7d, 0x56, 0x40, 0xab, 0xc7, 0x82, 0xb8, 0xab, 0x60, 0x98, 0xe2, 0xb7, 0x40, 0x56,
	0x2f, 0x93, 0xb5, 0xc1, 0x3c, 0x87, 0xac, 0xff, 0x04, 0x31, 0x8f, 0xe2, 0x88, 0x63, 0x12, 0x0a,
	0xdb, 0xaa, 0x53, 0x86, 0x63, 0xe7, 0xee, 0x91, 0x1f, 0x20, 0x2e, 0x9c, 0xcf, 0x38, 0x49, 0x54,
	0x72, 0xbe, 0x0f, 0x16, 0xc6, 0x75, 0x65, 0x96, 0x4d, 0x00, 0x3c, 0x12, 0x72, 0x0a, 0x3d, 0x9e,
	0x79, 0x1e, 0x43, 0xa6, 0xec, 0x4a, 0xce, 0xdb, 0x18, 0xe7, 0xb5, 0xbe, 0xc8, 0x11, 0x38, 0x90,
	0x5f, 0x3b, 0x82, 0x7f, 0x37, 0x2f, 0xca, 0x6a, 0x54, 0x64, 0x2d, 0x81, 0x26, 0x85, 0xf1, 0xa8,
	0x52, 0xd3, 0x32, 0x12, 0x38, 0x3a, 0xc6, 0xe8, 0x44, 0x9f, 0x95, 0xc7, 0x40, 0x46, 0xa5, 0x61,
	0xbc, 0x10, 0xc3, 0xc8, 0x14, 0x66, 0xc3, 0xd0, 0xc1, 0x1c, 0x3b, 0xf2, 0x3c, 0xc4, 0x98, 0x50,
	0xfa, 0x9f, 0x93, 0x86, 0xf1, 0x66, 0x85, 0xe8, 0xc4, 0x91, 0x94, 0x72, 0xe3, 0x73, 0x60, 0xe3,
	0x4f, 0x1d, 0x34, 0x7a, 0x2c, 0xd0, 0xde, 0x80, 0x56, 0xe1, 0x16, 0x9b, 0xa5, 0xdb, 0x57, 0xba,
	0x2c, 0xc6, 0xbd, 0xe9, 0xf9, 0x4c, 0x97, 0x0b, 0x6e, 0x56, 0x2e, 0x92, 0x55, 0x5d, 0x5b, 0xae,
	0x31, 0x3a, 0xd7, 0xd7, 0x64, 0x1c, 0x3d, 0xa0, 0xe6, 0xa7, 0x76, 0xb5, 0xba, 0x30, 0x4b, 0x1a,
	0x77, 0xa7, 0x24, 0xc7, 0xdb, 0xe5, 0x27, 0x60, 0x42, 0xbb, 0x2c, 0x39, 0xa9, 0x5d, 0x65, 0x67,
	0x8c, 0xd9, 0x77, 0xf1, 0x63, 0xb5, 0x6d, 0x5f, 0x5c, 0x99, 0xca, 0xe5, 0x95, 0xa9, 0xfc, 0xbe,
	0x32, 0x95, 0x8f, 0x43, 0xb3, 0x76, 0x39, 0x34, 0x6b, 0x3f, 0x87, 0x66, 0xed, 0xed, 0x62, 0xf9,
	0xad, 0xe2, 0x67, 0x11, 0x62, 0x6e, 0x53, 0x3c, 0xb1, 0x0f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x8f, 0x94, 0xc7, 0x78, 0x04, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	ListAgentForHire(ctx context.Context, in *MsgListAgentForHire, opts ...grpc.CallOption) (*MsgListAgentForHireResponse, error)
	HireAgent(ctx context.Context, in *MsgHireAgent, opts ...grpc.CallOption) (*MsgHireAgentResponse, error)
	RateAgent(ctx context.Context, in *MsgRateAgent, opts ...grpc.CallOption) (*MsgRateAgentResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/qcb.qcbmarket.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ListAgentForHire(ctx context.Context, in *MsgListAgentForHire, opts ...grpc.CallOption) (*MsgListAgentForHireResponse, error) {
	out := new(MsgListAgentForHireResponse)
	err := c.cc.Invoke(ctx, "/qcb.qcbmarket.Msg/ListAgentForHire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) HireAgent(ctx context.Context, in *MsgHireAgent, opts ...grpc.CallOption) (*MsgHireAgentResponse, error) {
	out := new(MsgHireAgentResponse)
	err := c.cc.Invoke(ctx, "/qcb.qcbmarket.Msg/HireAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RateAgent(ctx context.Context, in *MsgRateAgent, opts ...grpc.CallOption) (*MsgRateAgentResponse, error) {
	out := new(MsgRateAgentResponse)
	err := c.cc.Invoke(ctx, "/qcb.qcbmarket.Msg/RateAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	ListAgentForHire(context.Context, *MsgListAgentForHire) (*MsgListAgentForHireResponse, error)
	HireAgent(context.Context, *MsgHireAgent) (*MsgHireAgentResponse, error)
	RateAgent(context.Context, *MsgRateAgent) (*MsgRateAgentResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) ListAgentForHire(ctx context.Context, req *MsgListAgentForHire) (*MsgListAgentForHireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentForHire not implemented")
}
func (*UnimplementedMsgServer) HireAgent(ctx context.Context, req *MsgHireAgent) (*MsgHireAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HireAgent not implemented")
}
func (*UnimplementedMsgServer) RateAgent(ctx context.Context, req *MsgRateAgent) (*MsgRateAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateAgent not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qcb.qcbmarket.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ListAgentForHire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgListAgentForHire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ListAgentForHire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qcb.qcbmarket.Msg/ListAgentForHire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ListAgentForHire(ctx, req.(*MsgListAgentForHire))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_HireAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgHireAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).HireAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qcb.qcbmarket.Msg/HireAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).HireAgent(ctx, req.(*MsgHireAgent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRateAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qcb.qcbmarket.Msg/RateAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RateAgent(ctx, req.(*MsgRateAgent))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qcb.qcbmarket.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "ListAgentForHire",
			Handler:    _Msg_ListAgentForHire_Handler,
		},
		{
			MethodName: "HireAgent",
			Handler:    _Msg_HireAgent_Handler,
		},
		{
			MethodName: "RateAgent",
			Handler:    _Msg_RateAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qcb/qcbmarket/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgListAgentForHire) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgListAgentForHire) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgListAgentForHire) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Skills) > 0 {
		i -= len(m.Skills)
		copy(dAtA[i:], m.Skills)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Skills)))
		i--
		dAtA[i] = 0x22
	}
	if m.PricePerTask != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PricePerTask))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgListAgentForHireResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgListAgentForHireResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgListAgentForHireResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PricePerTask != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PricePerTask))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ListingId) > 0 {
		i -= len(m.ListingId)
		copy(dAtA[i:], m.ListingId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ListingId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgHireAgent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgHireAgent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgHireAgent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Budget != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Budget))
		i--
		dAtA[i] = 0x20
	}
	if len(m.TaskDescription) > 0 {
		i -= len(m.TaskDescription)
		copy(dAtA[i:], m.TaskDescription)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TaskDescription)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ListingId) > 0 {
		i -= len(m.ListingId)
		copy(dAtA[i:], m.ListingId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ListingId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgHireAgentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgHireAgentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgHireAgentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Budget != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Budget))
		i--
		dAtA[i] = 0x18
	}
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ContractId) > 0 {
		i -= len(m.ContractId)
		copy(dAtA[i:], m.ContractId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRateAgent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRateAgent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRateAgent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Review) > 0 {
		i -= len(m.Review)
		copy(dAtA[i:], m.Review)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Review)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Rating != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Rating))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ContractId) > 0 {
		i -= len(m.ContractId)
		copy(dAtA[i:], m.ContractId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AgentId) > 0 {
		i -= len(m.AgentId)
		copy(dAtA[i:], m.AgentId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AgentId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRateAgentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRateAgentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRateAgentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewRating != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NewRating))
		i--
		dAtA[i] = 0x10
	}
	if m.Success {
		i--
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgListAgentForHire) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PricePerTask != 0 {
		n += 1 + sovTx(uint64(m.PricePerTask))
	}
	l = len(m.Skills)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgListAgentForHireResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ListingId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PricePerTask != 0 {
		n += 1 + sovTx(uint64(m.PricePerTask))
	}
	return n
}

func (m *MsgHireAgent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ListingId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TaskDescription)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Budget != 0 {
		n += 1 + sovTx(uint64(m.Budget))
	}
	return n
}

func (m *MsgHireAgentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Budget != 0 {
		n += 1 + sovTx(uint64(m.Budget))
	}
	return n
}

func (m *MsgRateAgent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AgentId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContractId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Rating != 0 {
		n += 1 + sovTx(uint64(m.Rating))
	}
	l = len(m.Review)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRateAgentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	if m.NewRating != 0 {
		n += 1 + sovTx(uint64(m.NewRating))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgListAgentForHire) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgListAgentForHire: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgListAgentForHire: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePerTask", wireType)
			}
			m.PricePerTask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PricePerTask |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skills", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Skills = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgListAgentForHireResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgListAgentForHireResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgListAgentForHireResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePerTask", wireType)
			}
			m.PricePerTask = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PricePerTask |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgHireAgent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgHireAgent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgHireAgent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListingId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListingId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budget", wireType)
			}
			m.Budget = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Budget |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgHireAgentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgHireAgentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgHireAgentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Budget", wireType)
			}
			m.Budget = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Budget |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRateAgent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRateAgent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRateAgent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AgentId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rating", wireType)
			}
			m.Rating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rating |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Review", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Review = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRateAgentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRateAgentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRateAgentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewRating", wireType)
			}
			m.NewRating = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewRating |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
